<?php
/**
 * AddonSecondaryLinkagePosition
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AddonSecondaryLinkagePosition Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonSecondaryLinkagePosition
{
    /**
     * Possible values of this enum
     */
    public const POST_SPEC_HEAD = 'POST_SPEC_HEAD';

    public const POST_SPEC_TAIL = 'POST_SPEC_TAIL';

    public const POST_PRICE_SPEC = 'POST_PRICE_SPEC';

    public const POST_DESC_TAIL = 'POST_DESC_TAIL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::POST_SPEC_HEAD,
            self::POST_SPEC_TAIL,
            self::POST_PRICE_SPEC,
            self::POST_DESC_TAIL
        ];
    }
}


