<?php
/**
 * AddonsWidgetColor
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AddonsWidgetColor Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonsWidgetColor
{
    /**
     * Possible values of this enum
     */
    public const WARNING_SECONDARY = 'WARNING_SECONDARY';

    public const WARNING_PRIMARY = 'WARNING_PRIMARY';

    public const ERROR_PRIMARY = 'ERROR_PRIMARY';

    public const SUCCESS_PRIMARY = 'SUCCESS_PRIMARY';

    public const SUCCESS_SECONDARY = 'SUCCESS_SECONDARY';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WARNING_SECONDARY,
            self::WARNING_PRIMARY,
            self::ERROR_PRIMARY,
            self::SUCCESS_PRIMARY,
            self::SUCCESS_SECONDARY
        ];
    }
}


