<?php
/**
 * AddonSemanticCarVerificationStage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AddonSemanticCarVerificationStage Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonSemanticCarVerificationStage
{
    /**
     * Possible values of this enum
     */
    public const CARVERIFICATIONSTAGE_NOT_STARTED = 'CARVERIFICATIONSTAGE_NOT_STARTED';

    public const CARVERIFICATIONSTAGE_SHAHKAR = 'CARVERIFICATIONSTAGE_SHAHKAR';

    public const CAR_CARD_VERIFICATION = 'CAR_CARD_VERIFICATION';

    public const CAR_MODEL_VERIFICATION = 'CAR_MODEL_VERIFICATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CARVERIFICATIONSTAGE_NOT_STARTED,
            self::CARVERIFICATIONSTAGE_SHAHKAR,
            self::CAR_CARD_VERIFICATION,
            self::CAR_MODEL_VERIFICATION
        ];
    }
}


