<?php
/**
 * AppsServiceType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AppsServiceType Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppsServiceType
{
    /**
     * Possible values of this enum
     */
    public const FUNC_CLICK_AND_COLLECT = 'FUNC_CLICK_AND_COLLECT';

    public const FUNC_DELIVERY = 'FUNC_DELIVERY';

    public const FUNC_SECURE_PAYMENT = 'FUNC_SECURE_PAYMENT';

    public const LEAD_GEN_PURE = 'LEAD_GEN_PURE';

    public const LEAD_GEN_LOAN = 'LEAD_GEN_LOAN';

    public const REPORT_INSPECTION = 'REPORT_INSPECTION';

    public const REPORT_PRICE_EVALUATION = 'REPORT_PRICE_EVALUATION';

    public const REPORT_VERIFICATION = 'REPORT_VERIFICATION';

    public const FUNC_CONTRACT = 'FUNC_CONTRACT';

    public const FUNC_FINANCING = 'FUNC_FINANCING';

    public const USER_FACE_ID_VERIFICATION = 'USER_FACE_ID_VERIFICATION';

    public const POST_VERIFICATION = 'POST_VERIFICATION';

    public const INTERNAL = 'INTERNAL';

    public const USER_BACKGROUND_VERIFICATION = 'USER_BACKGROUND_VERIFICATION';

    public const USER_BUSINESS_VERIFICATION = 'USER_BUSINESS_VERIFICATION';

    public const CHARITY = 'CHARITY';

    public const SECURE_PAYMENT_POST_PROMOTION = 'SECURE_PAYMENT_POST_PROMOTION';

    public const PHOTOGRAPHY = 'PHOTOGRAPHY';

    public const DOWNLOADABLE_CONTENT_GENERATION = 'DOWNLOADABLE_CONTENT_GENERATION';

    public const REPORT_INSPECTION_CHAT = 'REPORT_INSPECTION_CHAT';

    public const ADDITIONAL_INFORMATION = 'ADDITIONAL_INFORMATION';

    public const ACCOUNTING = 'ACCOUNTING';

    public const ASSISTANT = 'ASSISTANT';

    public const ADVERTISEMENT = 'ADVERTISEMENT';

    public const CONTRACT_POST = 'CONTRACT_POST';

    public const SITE_BUILDER = 'SITE_BUILDER';

    public const FORM_BUILDER = 'FORM_BUILDER';

    public const AUCTION = 'AUCTION';

    public const POST_DETAIL_ENHANCER = 'POST_DETAIL_ENHANCER';

    public const POST_REORDER = 'POST_REORDER';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FUNC_CLICK_AND_COLLECT,
            self::FUNC_DELIVERY,
            self::FUNC_SECURE_PAYMENT,
            self::LEAD_GEN_PURE,
            self::LEAD_GEN_LOAN,
            self::REPORT_INSPECTION,
            self::REPORT_PRICE_EVALUATION,
            self::REPORT_VERIFICATION,
            self::FUNC_CONTRACT,
            self::FUNC_FINANCING,
            self::USER_FACE_ID_VERIFICATION,
            self::POST_VERIFICATION,
            self::INTERNAL,
            self::USER_BACKGROUND_VERIFICATION,
            self::USER_BUSINESS_VERIFICATION,
            self::CHARITY,
            self::SECURE_PAYMENT_POST_PROMOTION,
            self::PHOTOGRAPHY,
            self::DOWNLOADABLE_CONTENT_GENERATION,
            self::REPORT_INSPECTION_CHAT,
            self::ADDITIONAL_INFORMATION,
            self::ACCOUNTING,
            self::ASSISTANT,
            self::ADVERTISEMENT,
            self::CONTRACT_POST,
            self::SITE_BUILDER,
            self::FORM_BUILDER,
            self::AUCTION,
            self::POST_DETAIL_ENHANCER,
            self::POST_REORDER
        ];
    }
}


