<?php
/**
 * AppsServiceTag
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AppsServiceTag Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppsServiceTag
{
    /**
     * Possible values of this enum
     */
    public const VERIFIED = 'VERIFIED';

    public const IDENTITY_VERIFIED = 'IDENTITY_VERIFIED';

    public const POST_VERIFIED = 'POST_VERIFIED';

    public const SECURE_PAYMENT = 'SECURE_PAYMENT';

    public const POST_OWNERSHIP_VERIFIED = 'POST_OWNERSHIP_VERIFIED';

    public const EXPERT_INSPECTED = 'EXPERT_INSPECTED';

    public const CAR_EXPERT_INSPECTED = 'CAR_EXPERT_INSPECTED';

    public const HOME_EXPERT_INSPECTED = 'HOME_EXPERT_INSPECTED';

    public const MOBILE_EXPERT_INSPECTED = 'MOBILE_EXPERT_INSPECTED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VERIFIED,
            self::IDENTITY_VERIFIED,
            self::POST_VERIFIED,
            self::SECURE_PAYMENT,
            self::POST_OWNERSHIP_VERIFIED,
            self::EXPERT_INSPECTED,
            self::CAR_EXPERT_INSPECTED,
            self::HOME_EXPERT_INSPECTED,
            self::MOBILE_EXPERT_INSPECTED
        ];
    }
}


