<?php
/**
 * AssetsGetPermissionsResponseLifeCycleState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * AssetsGetPermissionsResponseLifeCycleState Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AssetsGetPermissionsResponseLifeCycleState
{
    /**
     * Possible values of this enum
     */
    public const EXPERIMENTAL = 'EXPERIMENTAL';

    public const ACTIVE = 'ACTIVE';

    public const DEPRECATING_SOON = 'DEPRECATING_SOON';

    public const DEPRECATED = 'DEPRECATED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPERIMENTAL,
            self::ACTIVE,
            self::DEPRECATING_SOON,
            self::DEPRECATED
        ];
    }
}


