<?php
/**
 * DivarIconsIconName
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * DivarIconsIconName Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DivarIconsIconName
{
    /**
     * Possible values of this enum
     */
    public const KEYBOARD_ARROW_RIGHT = 'KEYBOARD_ARROW_RIGHT';

    public const KEYBOARD_ARROW_LEFT = 'KEYBOARD_ARROW_LEFT';

    public const ARROW_FORWARD = 'ARROW_FORWARD';

    public const REFRESH = 'REFRESH';

    public const REMOVE = 'REMOVE';

    public const SEND = 'SEND';

    public const DELETE = 'DELETE';

    public const PHOTO_LIBRARY = 'PHOTO_LIBRARY';

    public const ADD = 'ADD';

    public const CLOSE = 'CLOSE';

    public const CHECKED = 'CHECKED';

    public const CHECK_BOX = 'CHECK_BOX';

    public const CHECK_BOX_OUTLINE_BLANK = 'CHECK_BOX_OUTLINE_BLANK';

    public const CHAT_DOUBLE = 'CHAT_DOUBLE';

    public const CONTENT_COPY = 'CONTENT_COPY';

    public const REPORT = 'REPORT';

    public const CAT_VEHICLES = 'CAT_VEHICLES';

    public const PERSON = 'PERSON';

    public const CALL = 'CALL';

    public const CAT_ELECTRONIC_DEVICES = 'CAT_ELECTRONIC_DEVICES';

    public const PLACE = 'PLACE';

    public const HISTORY = 'HISTORY';

    public const CHECK_CIRCLE = 'CHECK_CIRCLE';

    public const ACCESS_TIME = 'ACCESS_TIME';

    public const INFO_OUTLINE = 'INFO_OUTLINE';

    public const PAYMENT = 'PAYMENT';

    public const SHOW_CHART = 'SHOW_CHART';

    public const CONTACT_PHONE = 'CONTACT_PHONE';

    public const TRENDING_UP = 'TRENDING_UP';

    public const CAR_BODY = 'CAR_BODY';

    public const INSPECT = 'INSPECT';

    public const CAR_TIRES = 'CAR_TIRES';

    public const CAR_ELECTRONICS = 'CAR_ELECTRONICS';

    public const CAR_ENGINE = 'CAR_ENGINE';

    public const CAR_HYDRAULICS = 'CAR_HYDRAULICS';

    public const CAR_OPTIONS = 'CAR_OPTIONS';

    public const CAR_DOCUMENTS = 'CAR_DOCUMENTS';

    public const CANCEL = 'CANCEL';

    public const WARNING = 'WARNING';

    public const HELP = 'HELP';

    public const MONEY = 'MONEY';

    public const KARNAMEH = 'KARNAMEH';

    public const EDIT = 'EDIT';

    public const SUPPORT = 'SUPPORT';

    public const CAR_INSPECTED = 'CAR_INSPECTED';

    public const TERMS = 'TERMS';

    public const LADDER_COLLECTION = 'LADDER_COLLECTION';

    public const HOUSE_INSPECTION = 'HOUSE_INSPECTION';

    public const ADD_CIRCLE = 'ADD_CIRCLE';

    public const GAVEL = 'GAVEL';

    public const LADDER_GROUP = 'LADDER_GROUP';

    public const VISIBILITY = 'VISIBILITY';

    public const TIMER = 'TIMER';

    public const LOCK = 'LOCK';

    public const BLOCK = 'BLOCK';

    public const EMAIL_OUTLINE = 'EMAIL_OUTLINE';

    public const ASSIGNMENT_IND = 'ASSIGNMENT_IND';

    public const TOC = 'TOC';

    public const EXIT_TO_APP = 'EXIT_TO_APP';

    public const HELP_OUTLINE = 'HELP_OUTLINE';

    public const TELEPHONE = 'TELEPHONE';

    public const EVENT_NOTE = 'EVENT_NOTE';

    public const COMMUNITY = 'COMMUNITY';

    public const REAL_ESTATE = 'REAL_ESTATE';

    public const VR = 'VR';

    public const NUM_1 = 'NUM_1';

    public const NUM_2 = 'NUM_2';

    public const NUM_3 = 'NUM_3';

    public const NUM_4 = 'NUM_4';

    public const NUM_5 = 'NUM_5';

    public const NUM_6 = 'NUM_6';

    public const NUM_7 = 'NUM_7';

    public const NUM_8 = 'NUM_8';

    public const NUM_9 = 'NUM_9';

    public const ELEVATOR = 'ELEVATOR';

    public const PARKING = 'PARKING';

    public const CABINET = 'CABINET';

    public const BALCONY = 'BALCONY';

    public const TEXTURE = 'TEXTURE';

    public const WC = 'WC';

    public const SNOWFLAKE = 'SNOWFLAKE';

    public const SUNNY = 'SUNNY';

    public const THERMOMETER = 'THERMOMETER';

    public const VERIFIED = 'VERIFIED';

    public const SETTINGS = 'SETTINGS';

    public const CREDIT_ACCOUNT = 'CREDIT_ACCOUNT';

    public const CAR_AUCTION = 'CAR_AUCTION';

    public const CONCIERGE_SALE = 'CONCIERGE_SALE';

    public const INFO = 'INFO';

    public const MARKETPLACE_GENERAL = 'MARKETPLACE_GENERAL';

    public const MARKETPLACE_HOME = 'MARKETPLACE_HOME';

    public const MARKETPLACE_PERSONAL = 'MARKETPLACE_PERSONAL';

    public const MARKETPLACE_ELECTRONIC_DEVICES = 'MARKETPLACE_ELECTRONIC_DEVICES';

    public const INDICATOR_F = 'INDICATOR_F';

    public const SHARE = 'SHARE';

    public const CAR_INSPECTION = 'CAR_INSPECTION';

    public const VERIFIED_USER = 'VERIFIED_USER';

    public const MARKETPLACE_LIST = 'MARKETPLACE_LIST';

    public const BINDER = 'BINDER';

    public const STAR = 'STAR';

    public const CAR_AMENITY = 'CAR_AMENITY';

    public const CAR_SAFETY = 'CAR_SAFETY';

    public const CAR_EQUIPMENT = 'CAR_EQUIPMENT';

    public const BUSINESS_REAL_ESTATE_AGENCY = 'BUSINESS_REAL_ESTATE_AGENCY';

    public const BUSINESS_MARKETPLACE = 'BUSINESS_MARKETPLACE';

    public const BUSINESS_AUTO_DEALERSHIP = 'BUSINESS_AUTO_DEALERSHIP';

    public const LOCAL_SHIPPING = 'LOCAL_SHIPPING';

    public const MOPED = 'MOPED';

    public const TEXT_SMS_OUTLINE = 'TEXT_SMS_OUTLINE';

    public const PLACE_F = 'PLACE_F';

    public const MOBILE_FRIENDLY = 'MOBILE_FRIENDLY';

    public const STAR_BORDER = 'STAR_BORDER';

    public const IMAGE_OUTLINE = 'IMAGE_OUTLINE';

    public const ARTICLE_OUTLINE = 'ARTICLE_OUTLINE';

    public const POST_FEEDBACK = 'POST_FEEDBACK';

    public const DOWNLOAD = 'DOWNLOAD';

    public const FILTER = 'FILTER';

    public const SUPPORT_AGENT = 'SUPPORT_AGENT';

    public const MORE_VERT = 'MORE_VERT';

    public const BOOKMARK = 'BOOKMARK';

    public const BOOKMARK_BORDER = 'BOOKMARK_BORDER';

    public const GIFT = 'GIFT';

    public const ANALYTICS = 'ANALYTICS';

    public const STORE = 'STORE';

    public const STORE_OUTLINE = 'STORE_OUTLINE';

    public const CAT_BUSINESSES = 'CAT_BUSINESSES';

    public const CAT_FOR_THE_HOME = 'CAT_FOR_THE_HOME';

    public const CAT_SERVICES = 'CAT_SERVICES';

    public const CAT_PERSONAL = 'CAT_PERSONAL';

    public const CAT_LEISURE_HOBBIES = 'CAT_LEISURE_HOBBIES';

    public const CAT_JOBS = 'CAT_JOBS';

    public const SCHOOL = 'SCHOOL';

    public const NOTE = 'NOTE';

    public const LOGOUT = 'LOGOUT';

    public const PERSON_ADD = 'PERSON_ADD';

    public const ADVERT = 'ADVERT';

    public const ADVERT_OUTLINE = 'ADVERT_OUTLINE';

    public const ACCESS_TIME_OUTLINE = 'ACCESS_TIME_OUTLINE';

    public const NOTE_OUTLINE = 'NOTE_OUTLINE';

    public const PAYMENT_OUTLINE = 'PAYMENT_OUTLINE';

    public const INSTAGRAM = 'INSTAGRAM';

    public const TAG_CHECK_CIRCLE = 'TAG_CHECK_CIRCLE';

    public const FULLSCREEN = 'FULLSCREEN';

    public const ADD_CIRCLE_OUTLINE = 'ADD_CIRCLE_OUTLINE';

    public const NOTE_ADD_OUTLINE = 'NOTE_ADD_OUTLINE';

    public const BRAND_ALFA_ROMEO = 'BRAND_ALFA_ROMEO';

    public const BRAND_AMICO = 'BRAND_AMICO';

    public const BRAND_ARIO = 'BRAND_ARIO';

    public const BRAND_ARISAN = 'BRAND_ARISAN';

    public const BRAND_AUDI = 'BRAND_AUDI';

    public const BRAND_BAIC = 'BRAND_BAIC';

    public const BRAND_BESTURN = 'BRAND_BESTURN';

    public const BRAND_BISU = 'BRAND_BISU';

    public const BRAND_BMW = 'BRAND_BMW';

    public const BRAND_BORGWARD = 'BRAND_BORGWARD';

    public const BRAND_BRILLIANCE = 'BRAND_BRILLIANCE';

    public const BRAND_BUICK = 'BRAND_BUICK';

    public const BRAND_BYD = 'BRAND_BYD';

    public const BRAND_CAPRA = 'BRAND_CAPRA';

    public const BRAND_CHANGAN = 'BRAND_CHANGAN';

    public const BRAND_CHERY = 'BRAND_CHERY';

    public const BRAND_CHEVROLET = 'BRAND_CHEVROLET';

    public const BRAND_CITROEN = 'BRAND_CITROEN';

    public const BRAND_DAEWOO = 'BRAND_DAEWOO';

    public const BRAND_DATSUN = 'BRAND_DATSUN';

    public const BRAND_DEER = 'BRAND_DEER';

    public const BRAND_DELICA = 'BRAND_DELICA';

    public const BRAND_DENA = 'BRAND_DENA';

    public const BRAND_DIGNITY = 'BRAND_DIGNITY';

    public const BRAND_DODGE = 'BRAND_DODGE';

    public const BRAND_DOMY = 'BRAND_DOMY';

    public const BRAND_DONGFENG = 'BRAND_DONGFENG';

    public const BRAND_DS = 'BRAND_DS';

    public const BRAND_FARDA = 'BRAND_FARDA';

    public const BRAND_FAW = 'BRAND_FAW';

    public const BRAND_FIAT = 'BRAND_FIAT';

    public const BRAND_FIDELITY = 'BRAND_FIDELITY';

    public const BRAND_FORD = 'BRAND_FORD';

    public const BRAND_FOTON = 'BRAND_FOTON';

    public const BRAND_GAC_GONOW = 'BRAND_GAC_GONOW';

    public const BRAND_GEELY = 'BRAND_GEELY';

    public const BRAND_GREATWALL = 'BRAND_GREATWALL';

    public const BRAND_HAFEI_LOBO = 'BRAND_HAFEI_LOBO';

    public const BRAND_HAIMA = 'BRAND_HAIMA';

    public const BRAND_HANTENG = 'BRAND_HANTENG';

    public const BRAND_HAVAL = 'BRAND_HAVAL';

    public const BRAND_HILLMAN = 'BRAND_HILLMAN';

    public const BRAND_HONDA = 'BRAND_HONDA';

    public const BRAND_HUMMER = 'BRAND_HUMMER';

    public const BRAND_HYOSOW = 'BRAND_HYOSOW';

    public const BRAND_HYUNDAI = 'BRAND_HYUNDAI';

    public const BRAND_IRANKHODRO_VAN = 'BRAND_IRANKHODRO_VAN';

    public const BRAND_ISUZU = 'BRAND_ISUZU';

    public const BRAND_IVECO = 'BRAND_IVECO';

    public const BRAND_JAC = 'BRAND_JAC';

    public const BRAND_JAGUAR = 'BRAND_JAGUAR';

    public const BRAND_JEEP = 'BRAND_JEEP';

    public const BRAND_JMC = 'BRAND_JMC';

    public const BRAND_JOYLONG = 'BRAND_JOYLONG';

    public const BRAND_KIA = 'BRAND_KIA';

    public const BRAND_KMC = 'BRAND_KMC';

    public const BRAND_LADA = 'BRAND_LADA';

    public const BRAND_LAMBORGHINI = 'BRAND_LAMBORGHINI';

    public const BRAND_LAND_ROVER = 'BRAND_LAND_ROVER';

    public const BRAND_LANDMARK = 'BRAND_LANDMARK';

    public const BRAND_LEXUS = 'BRAND_LEXUS';

    public const BRAND_LIFAN = 'BRAND_LIFAN';

    public const BRAND_LOTUS = 'BRAND_LOTUS';

    public const BRAND_LUXGEN = 'BRAND_LUXGEN';

    public const BRAND_MASERATI = 'BRAND_MASERATI';

    public const BRAND_MAXUS = 'BRAND_MAXUS';

    public const BRAND_MAZDA = 'BRAND_MAZDA';

    public const BRAND_MERCEDESBENZ = 'BRAND_MERCEDESBENZ';

    public const BRAND_MG = 'BRAND_MG';

    public const BRAND_MINI = 'BRAND_MINI';

    public const BRAND_MITSUBISHI = 'BRAND_MITSUBISHI';

    public const BRAND_MVM = 'BRAND_MVM';

    public const BRAND_NARVAN = 'BRAND_NARVAN';

    public const BRAND_NISSAN = 'BRAND_NISSAN';

    public const BRAND_OLDSMOBILE = 'BRAND_OLDSMOBILE';

    public const BRAND_OPEL = 'BRAND_OPEL';

    public const BRAND_PAYKAN = 'BRAND_PAYKAN';

    public const BRAND_PAZHAN = 'BRAND_PAZHAN';

    public const BRAND_PEUGEOT = 'BRAND_PEUGEOT';

    public const BRAND_PONTIAC = 'BRAND_PONTIAC';

    public const BRAND_PORSCHE = 'BRAND_PORSCHE';

    public const BRAND_PRIDE = 'BRAND_PRIDE';

    public const BRAND_PROTON = 'BRAND_PROTON';

    public const BRAND_QUICK = 'BRAND_QUICK';

    public const BRAND_RAYEN = 'BRAND_RAYEN';

    public const BRAND_RENAULT = 'BRAND_RENAULT';

    public const BRAND_RICH = 'BRAND_RICH';

    public const BRAND_RIGAN = 'BRAND_RIGAN';

    public const BRAND_RUNNA = 'BRAND_RUNNA';

    public const BRAND_SAINA = 'BRAND_SAINA';

    public const BRAND_SAIPA = 'BRAND_SAIPA';

    public const BRAND_SAMAND = 'BRAND_SAMAND';

    public const BRAND_SEAT = 'BRAND_SEAT';

    public const BRAND_SHAHIN = 'BRAND_SHAHIN';

    public const BRAND_SINAD = 'BRAND_SINAD';

    public const BRAND_SMART = 'BRAND_SMART';

    public const BRAND_SSANGYONG = 'BRAND_SSANGYONG';

    public const BRAND_SUBARU = 'BRAND_SUBARU';

    public const BRAND_SUZUKI = 'BRAND_SUZUKI';

    public const BRAND_SWM = 'BRAND_SWM';

    public const BRAND_TARA = 'BRAND_TARA';

    public const BRAND_TIBA = 'BRAND_TIBA';

    public const BRAND_TOYOTA = 'BRAND_TOYOTA';

    public const BRAND_UAZ = 'BRAND_UAZ';

    public const BRAND_VOLKSWAGEN = 'BRAND_VOLKSWAGEN';

    public const BRAND_VOLVO = 'BRAND_VOLVO';

    public const BRAND_ZAMYAD = 'BRAND_ZAMYAD';

    public const BRAND_ZOTYE = 'BRAND_ZOTYE';

    public const BRAND_SOUEAST = 'BRAND_SOUEAST';

    public const ARCHWAY = 'ARCHWAY';

    public const METRO = 'METRO';

    public const POI = 'POI';

    public const STREET_SIGN = 'STREET_SIGN';

    public const TREES = 'TREES';

    public const EARNEST = 'EARNEST';

    public const RESTAURANT = 'RESTAURANT';

    public const BACKPACK = 'BACKPACK';

    public const STETHOSCOPE = 'STETHOSCOPE';

    public const MOSQUE = 'MOSQUE';

    public const HOSPITAL = 'HOSPITAL';

    public const CAPSULE = 'CAPSULE';

    public const BANK = 'BANK';

    public const CART = 'CART';

    public const SHOPPING = 'SHOPPING';

    public const BRAND_CHRYSLER = 'BRAND_CHRYSLER';

    public const BRAND_DAIHATSU = 'BRAND_DAIHATSU';

    public const BRAND_FOWNIX = 'BRAND_FOWNIX';

    public const BRAND_ROLLSROYCE = 'BRAND_ROLLSROYCE';

    public const TUNE = 'TUNE';

    public const EXCHANGE = 'EXCHANGE';

    public const BABY = 'BABY';

    public const BAGUETTE = 'BAGUETTE';

    public const BUS = 'BUS';

    public const COFFEE = 'COFFEE';

    public const FRUIT = 'FRUIT';

    public const GAS_STATION = 'GAS_STATION';

    public const GYM = 'GYM';

    public const HAMBURGER = 'HAMBURGER';

    public const HIGHWAY = 'HIGHWAY';

    public const MEDIC = 'MEDIC';

    public const SCHOOL_OUTLINE = 'SCHOOL_OUTLINE';

    public const TAXI = 'TAXI';

    public const CAMERA = 'CAMERA';

    public const CAMERA_O = 'CAMERA_O';

    public const EYE_OFF = 'EYE_OFF';

    public const BRAND_DAYUN = 'BRAND_DAYUN';

    public const BRAND_MAXMOTOR = 'BRAND_MAXMOTOR';

    public const VIDEOCAM = 'VIDEOCAM';

    public const BRAND_ACER = 'BRAND_ACER';

    public const BRAND_ALCATEL = 'BRAND_ALCATEL';

    public const BRAND_AMAZON = 'BRAND_AMAZON';

    public const BRAND_APPLE = 'BRAND_APPLE';

    public const BRAND_ARCHOS = 'BRAND_ARCHOS';

    public const BRAND_ASUS = 'BRAND_ASUS';

    public const BRAND_BLACKBERRY = 'BRAND_BLACKBERRY';

    public const BRAND_BLU = 'BRAND_BLU';

    public const BRAND_CATERPILLAR = 'BRAND_CATERPILLAR';

    public const BRAND_ENERGIZER = 'BRAND_ENERGIZER';

    public const BRAND_GIGABYTE = 'BRAND_GIGABYTE';

    public const BRAND_GIONEE = 'BRAND_GIONEE';

    public const BRAND_GLX = 'BRAND_GLX';

    public const BRAND_GOOGLE = 'BRAND_GOOGLE';

    public const BRAND_GPLUS = 'BRAND_GPLUS';

    public const BRAND_HONOR = 'BRAND_HONOR';

    public const BRAND_HTC = 'BRAND_HTC';

    public const BRAND_HUAWEI = 'BRAND_HUAWEI';

    public const BRAND_LENOVO = 'BRAND_LENOVO';

    public const BRAND_LG = 'BRAND_LG';

    public const BRAND_MEIZU = 'BRAND_MEIZU';

    public const BRAND_MICROMAX = 'BRAND_MICROMAX';

    public const BRAND_MICROSOFT = 'BRAND_MICROSOFT';

    public const BRAND_MOTOROLA = 'BRAND_MOTOROLA';

    public const BRAND_NOKIA = 'BRAND_NOKIA';

    public const BRAND_ONEPLUS = 'BRAND_ONEPLUS';

    public const BRAND_OPPO = 'BRAND_OPPO';

    public const BRAND_PANASONIC = 'BRAND_PANASONIC';

    public const BRAND_PHILIPS = 'BRAND_PHILIPS';

    public const BRAND_PIXEL = 'BRAND_PIXEL';

    public const BRAND_PRESTIGIO = 'BRAND_PRESTIGIO';

    public const BRAND_RAZER = 'BRAND_RAZER';

    public const BRAND_REALME = 'BRAND_REALME';

    public const BRAND_SAMSUNG = 'BRAND_SAMSUNG';

    public const BRAND_SHARP = 'BRAND_SHARP';

    public const BRAND_SONY_ERICSSON = 'BRAND_SONY_ERICSSON';

    public const BRAND_SONY = 'BRAND_SONY';

    public const BRAND_VERTU = 'BRAND_VERTU';

    public const BRAND_VIVO = 'BRAND_VIVO';

    public const BRAND_XIAOMI = 'BRAND_XIAOMI';

    public const BRAND_YOTA = 'BRAND_YOTA';

    public const BRAND_ZTE = 'BRAND_ZTE';

    public const BRAND_INROADS = 'BRAND_INROADS';

    public const VIDEOCAM_O = 'VIDEOCAM_O';

    public const SHIELD_PHONE = 'SHIELD_PHONE';

    public const SHIELD_PHONE_O = 'SHIELD_PHONE_O';

    public const BRAND_LAMARI = 'BRAND_LAMARI';

    public const VERIFIED_GREEN = 'VERIFIED_GREEN';

    public const CHART = 'CHART';

    public const CHART_O = 'CHART_O';

    public const LAUNCH = 'LAUNCH';

    public const WALLET = 'WALLET';

    public const TRASH_O = 'TRASH_O';

    public const TRASH_F = 'TRASH_F';

    public const BRAND_RESPECT = 'BRAND_RESPECT';

    public const BRAND_TIGARD = 'BRAND_TIGARD';

    public const FILE = 'FILE';

    public const FILE_O = 'FILE_O';

    public const IMAGE_OUTLINE_O = 'IMAGE_OUTLINE_O';

    public const CONTACT_PHONE_O = 'CONTACT_PHONE_O';

    public const PUZZLE = 'PUZZLE';

    public const PUZZLE_OUTLINE = 'PUZZLE_OUTLINE';

    public const CALL_OUTGOING = 'CALL_OUTGOING';

    public const CALL_INCOMING = 'CALL_INCOMING';

    public const CALL_MISSED = 'CALL_MISSED';

    public const CALL_BLOCKED = 'CALL_BLOCKED';

    public const ARCHIVE = 'ARCHIVE';

    public const ARCHIVE_O = 'ARCHIVE_O';

    public const CHAT_BUBBLE = 'CHAT_BUBBLE';

    public const CHAT_BUBBLE_F = 'CHAT_BUBBLE_F';

    public const MOBILE_1 = 'MOBILE_1';

    public const MOBILE_2 = 'MOBILE_2';

    public const MOBILE_3 = 'MOBILE_3';

    public const MOBILE_4 = 'MOBILE_4';

    public const MOBILE_5 = 'MOBILE_5';

    public const MOBILE_6 = 'MOBILE_6';

    public const MOBILE_7 = 'MOBILE_7';

    public const CARPET_1 = 'CARPET_1';

    public const CARPET_2 = 'CARPET_2';

    public const CARPET_3 = 'CARPET_3';

    public const CARPET_4 = 'CARPET_4';

    public const CARPET_5 = 'CARPET_5';

    public const CARPET_6 = 'CARPET_6';

    public const SOFA_1 = 'SOFA_1';

    public const SOFA_2 = 'SOFA_2';

    public const SOFA_3 = 'SOFA_3';

    public const SOFA_4 = 'SOFA_4';

    public const SOFA_5 = 'SOFA_5';

    public const SOFA_6 = 'SOFA_6';

    public const LIGHTS_2 = 'LIGHTS_2';

    public const LIGHTS_1 = 'LIGHTS_1';

    public const LIGHTS_3 = 'LIGHTS_3';

    public const LIGHTS_4 = 'LIGHTS_4';

    public const LIGHTS_5 = 'LIGHTS_5';

    public const BATTERY_CHARGING = 'BATTERY_CHARGING';

    public const BATTERY_HORIZ_075 = 'BATTERY_HORIZ_075';

    public const BATTERY_PROFILE = 'BATTERY_PROFILE';

    public const BUILD_CIRCLE = 'BUILD_CIRCLE';

    public const HEADPHONES = 'HEADPHONES';

    public const INVENTORY = 'INVENTORY';

    public const SMARTPHONE = 'SMARTPHONE';

    public const HOME_INSPECTION = 'HOME_INSPECTION';

    public const MOBILE_INSPECTION = 'MOBILE_INSPECTION';

    public const CAR_COLOR_BLUE = 'CAR_COLOR_BLUE';

    public const CAR_COLOR_CHERRY = 'CAR_COLOR_CHERRY';

    public const CAR_COLOR_PERSIANBLUE = 'CAR_COLOR_PERSIANBLUE';

    public const CAR_COLOR_EGGPLANT = 'CAR_COLOR_EGGPLANT';

    public const CAR_COLOR_BRONZE = 'CAR_COLOR_BRONZE';

    public const CAR_COLOR_BEIGE = 'CAR_COLOR_BEIGE';

    public const CAR_COLOR_PURPLE = 'CAR_COLOR_PURPLE';

    public const CAR_COLOR_ONIONSKIN = 'CAR_COLOR_ONIONSKIN';

    public const CAR_COLOR_TITANIUM = 'CAR_COLOR_TITANIUM';

    public const CAR_COLOR_GRAY = 'CAR_COLOR_GRAY';

    public const CAR_COLOR_KHAKI = 'CAR_COLOR_KHAKI';

    public const CAR_COLOR_SLATEGRAY = 'CAR_COLOR_SLATEGRAY';

    public const CAR_COLOR_CHARCOAL = 'CAR_COLOR_CHARCOAL';

    public const CAR_COLOR_YELLOW = 'CAR_COLOR_YELLOW';

    public const CAR_COLOR_CRIMSON = 'CAR_COLOR_CRIMSON';

    public const CAR_COLOR_OLIVE = 'CAR_COLOR_OLIVE';

    public const CAR_COLOR_GREEN = 'CAR_COLOR_GREEN';

    public const CAR_COLOR_LIGHTSLATEGRAY = 'CAR_COLOR_LIGHTSLATEGRAY';

    public const CAR_COLOR_NAVYBLUE = 'CAR_COLOR_NAVYBLUE';

    public const CAR_COLOR_WHITE = 'CAR_COLOR_WHITE';

    public const CAR_COLOR_OYSTERWHITE = 'CAR_COLOR_OYSTERWHITE';

    public const CAR_COLOR_GOLDEN = 'CAR_COLOR_GOLDEN';

    public const CAR_COLOR_LIGHTGRAY = 'CAR_COLOR_LIGHTGRAY';

    public const CAR_COLOR_WARMGRAY = 'CAR_COLOR_WARMGRAY';

    public const CAR_COLOR_JUJUBE = 'CAR_COLOR_JUJUBE';

    public const CAR_COLOR_RED = 'CAR_COLOR_RED';

    public const CAR_COLOR_BROWN = 'CAR_COLOR_BROWN';

    public const CAR_COLOR_CARBONBLACK = 'CAR_COLOR_CARBONBLACK';

    public const CAR_COLOR_DARKRED = 'CAR_COLOR_DARKRED';

    public const CAR_COLOR_COPPER = 'CAR_COLOR_COPPER';

    public const CAR_COLOR_BLACK = 'CAR_COLOR_BLACK';

    public const CAR_COLOR_MOCHA = 'CAR_COLOR_MOCHA';

    public const CAR_COLOR_ORANGE = 'CAR_COLOR_ORANGE';

    public const CAR_COLOR_BLUESILVER = 'CAR_COLOR_BLUESILVER';

    public const CAR_COLOR_SILVER = 'CAR_COLOR_SILVER';

    public const CAR_COLOR_DIMGRAY = 'CAR_COLOR_DIMGRAY';

    public const CAR_COLOR_JADEGREEN = 'CAR_COLOR_JADEGREEN';

    public const DIVAR_LOGO = 'DIVAR_LOGO';

    public const CAR_COLOR_CREAM = 'CAR_COLOR_CREAM';

    public const CAR_FRONT_SIDE = 'CAR_FRONT_SIDE';

    public const CAR_BACK_SIDE = 'CAR_BACK_SIDE';

    public const CAR_DRIVER_SIDE = 'CAR_DRIVER_SIDE';

    public const CAR_PASSENGER_SIDE = 'CAR_PASSENGER_SIDE';

    public const CAR_ODOMETER = 'CAR_ODOMETER';

    public const CRAFTSMEN = 'CRAFTSMEN';

    public const KITCHEN_UTENSILS = 'KITCHEN_UTENSILS';

    public const STOVES_HEATERS_FIREPLACES = 'STOVES_HEATERS_FIREPLACES';

    public const TRAVEL_PACKAGES = 'TRAVEL_PACKAGES';

    public const WATER_HEATER_PACKAGE_RADIATOR = 'WATER_HEATER_PACKAGE_RADIATOR';

    public const STAIRS = 'STAIRS';

    public const ACCESSIBILITY = 'ACCESSIBILITY';

    public const MAP_VIEW = 'MAP_VIEW';

    public const THUMB_DOWN = 'THUMB_DOWN';

    public const THUMB_UP = 'THUMB_UP';

    public const VIDEOCAM_PLUS = 'VIDEOCAM_PLUS';

    public const BADGE = 'BADGE';

    public const BADGE_F = 'BADGE_F';

    public const RADIO_BUTTON_UNCHECKED = 'RADIO_BUTTON_UNCHECKED';

    public const POLICE = 'POLICE';

    public const SORT_ASCENDING = 'SORT_ASCENDING';

    public const BUSINESS_PERSONAL = 'BUSINESS_PERSONAL';

    public const BRAND_XTRIM = 'BRAND_XTRIM';

    public const BRAND_BESTUNE = 'BRAND_BESTUNE';

    public const BRAND_GAC = 'BRAND_GAC';

    public const BRAND_VENUCIA = 'BRAND_VENUCIA';

    public const BRAND_VGV = 'BRAND_VGV';

    public const BRAND_ZX_AUTO = 'BRAND_ZX_AUTO';

    public const BRAND_QINGLING = 'BRAND_QINGLING';

    public const BUSINESS_JOBS = 'BUSINESS_JOBS';

    public const SHIELD_CHECK_CIRCLE = 'SHIELD_CHECK_CIRCLE';

    public const SCRIPT_TEXT = 'SCRIPT_TEXT';

    public const DOT_INDICATOR = 'DOT_INDICATOR';

    public const CLOCK = 'CLOCK';

    public const MAP_MARKER = 'MAP_MARKER';

    public const TOMAN_SIGN = 'TOMAN_SIGN';

    public const CHECK_DECOGRAM = 'CHECK_DECOGRAM';

    public const LADDER = 'LADDER';

    public const RUNNING_MAN = 'RUNNING_MAN';

    public const CALENDAR_TEXT = 'CALENDAR_TEXT';

    public const HOME = 'HOME';

    public const ADMINISTRATIVE_DOC = 'ADMINISTRATIVE_DOC';

    public const ANALOG_WATCH = 'ANALOG_WATCH';

    public const ANKLE_BOOTS = 'ANKLE_BOOTS';

    public const BARTER = 'BARTER';

    public const BOOTS = 'BOOTS';

    public const BRIEFCASE = 'BRIEFCASE';

    public const CAPACITY = 'CAPACITY';

    public const CARPET_DIMENSIONS = 'CARPET_DIMENSIONS';

    public const CHAIRS = 'CHAIRS';

    public const CHANDELIER = 'CHANDELIER';

    public const COLOR_BEAKER = 'COLOR_BEAKER';

    public const CONDITION = 'CONDITION';

    public const CONTROLLER = 'CONTROLLER';

    public const COSMETICS = 'COSMETICS';

    public const CPU = 'CPU';

    public const DIGITAL_WATCH = 'DIGITAL_WATCH';

    public const DOOR = 'DOOR';

    public const DRESS_SHOES = 'DRESS_SHOES';

    public const ELECTRICAL = 'ELECTRICAL';

    public const FAKE_BADGE = 'FAKE_BADGE';

    public const FANNY_PACK = 'FANNY_PACK';

    public const FURNITURE = 'FURNITURE';

    public const FURNITURE_CLASSIC = 'FURNITURE_CLASSIC';

    public const FURNITURE_SOFA = 'FURNITURE_SOFA';

    public const HANDBAG = 'HANDBAG';

    public const HDMI = 'HDMI';

    public const HERBAL_PILLS = 'HERBAL_PILLS';

    public const HOME_AREA = 'HOME_AREA';

    public const INSTALLMENT_SALE = 'INSTALLMENT_SALE';

    public const IRANCELL = 'IRANCELL';

    public const IRAN_MAP = 'IRAN_MAP';

    public const JEWELRY_ANKLET = 'JEWELRY_ANKLET';

    public const JEWELRY_BRACELET = 'JEWELRY_BRACELET';

    public const JEWELRY_EARRINGS = 'JEWELRY_EARRINGS';

    public const JEWELRY_NECKLACE = 'JEWELRY_NECKLACE';

    public const JEWELRY_RING = 'JEWELRY_RING';

    public const JEWELRY_SET = 'JEWELRY_SET';

    public const LAN = 'LAN';

    public const LOAFERS = 'LOAFERS';

    public const MAN = 'MAN';

    public const MAN_AND_WOMAN = 'MAN_AND_WOMAN';

    public const MATERIAL = 'MATERIAL';

    public const MCI = 'MCI';

    public const MEDICAL = 'MEDICAL';

    public const MEMORY = 'MEMORY';

    public const MODEM = 'MODEM';

    public const MONEY_BILLS = 'MONEY_BILLS';

    public const NINTENDO = 'NINTENDO';

    public const ORIGINAL_BADGE = 'ORIGINAL_BADGE';

    public const PAPER_DEED = 'PAPER_DEED';

    public const PARKING_LOT = 'PARKING_LOT';

    public const PERFUMES = 'PERFUMES';

    public const PLAY_STATION = 'PLAY_STATION';

    public const RAM = 'RAM';

    public const RECEIVING_HAND = 'RECEIVING_HAND';

    public const RIGHTEL = 'RIGHTEL';

    public const SANDALS = 'SANDALS';

    public const SCISSORS = 'SCISSORS';

    public const SCREEN_SIZE = 'SCREEN_SIZE';

    public const SHAKING_HANDS = 'SHAKING_HANDS';

    public const SHOULDER_BAG = 'SHOULDER_BAG';

    public const SIDE_TABLE = 'SIDE_TABLE';

    public const SIM = 'SIM';

    public const SIM_HOLDER = 'SIM_HOLDER';

    public const SKIN_CARE = 'SKIN_CARE';

    public const SLIPPERS = 'SLIPPERS';

    public const SMART_WATCH = 'SMART_WATCH';

    public const SNEAKERS = 'SNEAKERS';

    public const SPEEDOMETER = 'SPEEDOMETER';

    public const SPORT_BAG = 'SPORT_BAG';

    public const STAIRCASE = 'STAIRCASE';

    public const STORAGE = 'STORAGE';

    public const UMBRELLA = 'UMBRELLA';

    public const USB = 'USB';

    public const WOMAN = 'WOMAN';

    public const WORLD_MAP = 'WORLD_MAP';

    public const XBOX = 'XBOX';

    public const SHIELD_CHECK = 'SHIELD_CHECK';

    public const CAR = 'CAR';

    public const BUILDING = 'BUILDING';

    public const STOP_WATCH = 'STOP_WATCH';

    public const CHATBOT = 'CHATBOT';

    public const CHATBOT_OUTLINE = 'CHATBOT_OUTLINE';

    public const APARTMENT_RENT = 'APARTMENT_RENT';

    public const APARTMENT_SELL = 'APARTMENT_SELL';

    public const COMMERCIAL_RENT = 'COMMERCIAL_RENT';

    public const COMMERCIAL_SELL = 'COMMERCIAL_SELL';

    public const HOUSE_VILLA_RENT = 'HOUSE_VILLA_RENT';

    public const HOUSE_VILLA_SELL = 'HOUSE_VILLA_SELL';

    public const INDUSTRY_AGRICULTURE_BUSINESS_RENT = 'INDUSTRY_AGRICULTURE_BUSINESS_RENT';

    public const INDUSTRY_AGRICULTURE_BUSINESS_SELL = 'INDUSTRY_AGRICULTURE_BUSINESS_SELL';

    public const OFFICE_RENT = 'OFFICE_RENT';

    public const OFFICE_SELL = 'OFFICE_SELL';

    public const PARTNERSHIP = 'PARTNERSHIP';

    public const PLOT_OLD = 'PLOT_OLD';

    public const PRESELL = 'PRESELL';

    public const REAL_ESTATE_SERVICES = 'REAL_ESTATE_SERVICES';

    public const RESIDENTIAL_RENT = 'RESIDENTIAL_RENT';

    public const RESIDENTIAL_SELL = 'RESIDENTIAL_SELL';

    public const SHOP_RENT = 'SHOP_RENT';

    public const SHOP_SELL = 'SHOP_SELL';

    public const SUITE_APARTMENT = 'SUITE_APARTMENT';

    public const TEMPORARY_RENT = 'TEMPORARY_RENT';

    public const VILLA = 'VILLA';

    public const WORKSPACE = 'WORKSPACE';

    public const IMAGE_MULTIPLE = 'IMAGE_MULTIPLE';

    public const SHATEL_MOBILE = 'SHATEL_MOBILE';

    public const MEGAPHONE_F = 'MEGAPHONE_F';

    public const MEGAPHONE = 'MEGAPHONE';

    public const YEKTANET = 'YEKTANET';

    public const TAPSELL = 'TAPSELL';

    public const DAART = 'DAART';

    public const CLOSE_CIRCLE = 'CLOSE_CIRCLE';

    public const CLOSE_CIRCLE_F = 'CLOSE_CIRCLE_F';

    public const ACCESSORIES = 'ACCESSORIES';

    public const ACCOUNTING_AND_FINANCE = 'ACCOUNTING_AND_FINANCE';

    public const ACCOUNTING_FINANCE_LEGAL = 'ACCOUNTING_FINANCE_LEGAL';

    public const ADMINISTRATION_AND_HR = 'ADMINISTRATION_AND_HR';

    public const AIR_CONDITIONING_FAN_COIL = 'AIR_CONDITIONING_FAN_COIL';

    public const ANIMALS = 'ANIMALS';

    public const APPLIANCE = 'APPLIANCE';

    public const ARTIFICIAL_FLOWER = 'ARTIFICIAL_FLOWER';

    public const AUDIO_VIDEO = 'AUDIO_VIDEO';

    public const BABY_AND_TOYS = 'BABY_AND_TOYS';

    public const BALL_SPORTS = 'BALL_SPORTS';

    public const BARBERSHOP_AND_BEAUTYSALON = 'BARBERSHOP_AND_BEAUTYSALON';

    public const BATCH = 'BATCH';

    public const BATHROOMS = 'BATHROOMS';

    public const BATHROOM_ACCESSORIES = 'BATHROOM_ACCESSORIES';

    public const BEAUTY_AND_HAIRCARE = 'BEAUTY_AND_HAIRCARE';

    public const BED_PILLOW_BLANKET = 'BED_PILLOW_BLANKET';

    public const BED_SERVICE = 'BED_SERVICE';

    public const BED_SHEET = 'BED_SHEET';

    public const BICYCLE = 'BICYCLE';

    public const BIRDS = 'BIRDS';

    public const BOAT = 'BOAT';

    public const BOOKCASE_SHELF = 'BOOKCASE_SHELF';

    public const BOOK_STUDENT_LITERATURE = 'BOOK_STUDENT_LITERATURE';

    public const BUFFET_SHOWCASES = 'BUFFET_SHOWCASES';

    public const BUILDING_EQUIPMENT = 'BUILDING_EQUIPMENT';

    public const BUS_METRO_TRAIN = 'BUS_METRO_TRAIN';

    public const CAFE_AND_RESTAURANT = 'CAFE_AND_RESTAURANT';

    public const CAMERA_CAMCODERS = 'CAMERA_CAMCODERS';

    public const CAMPING_OUTDOOR = 'CAMPING_OUTDOOR';

    public const CARE_HEALTH_BEAUTY = 'CARE_HEALTH_BEAUTY';

    public const CARPET = 'CARPET';

    public const CARPET_MOQUETTE = 'CARPET_MOQUETTE';

    public const CARS = 'CARS';

    public const CAR_AND_MOTOR = 'CAR_AND_MOTOR';

    public const CAT = 'CAT';

    public const CATERING = 'CATERING';

    public const CCTV = 'CCTV';

    public const CHAIR_BENCH = 'CHAIR_BENCH';

    public const CHANDELIERS = 'CHANDELIERS';

    public const CHILDRENS_CLOTHING_AND_SHOE = 'CHILDRENS_CLOTHING_AND_SHOE';

    public const CHILDRENS_FURNITURE = 'CHILDRENS_FURNITURE';

    public const CHILD_CAR_SEAT = 'CHILD_CAR_SEAT';

    public const CLASSIC = 'CLASSIC';

    public const CLEANING = 'CLEANING';

    public const CLEANING_SUPPLIES = 'CLEANING_SUPPLIES';

    public const CLOTHES_RACK = 'CLOTHES_RACK';

    public const CLOTHING = 'CLOTHING';

    public const CLOTHING_AND_SHOES = 'CLOTHING_AND_SHOES';

    public const COIN_STAMP = 'COIN_STAMP';

    public const COMPUTERS = 'COMPUTERS';

    public const COMPUTER_AND_IT = 'COMPUTER_AND_IT';

    public const COMPUTER_AND_MOBILE = 'COMPUTER_AND_MOBILE';

    public const CONCERT = 'CONCERT';

    public const CONFERENCE_MEETING = 'CONFERENCE_MEETING';

    public const CONSTRUCTION_CRAFT = 'CONSTRUCTION_CRAFT';

    public const CONTAINERS = 'CONTAINERS';

    public const CONTAINER_ORGANIZERS = 'CONTAINER_ORGANIZERS';

    public const COOKING_UTENSILS = 'COOKING_UTENSILS';

    public const CRAFTS = 'CRAFTS';

    public const CURTAINS_TABLE_COVER = 'CURTAINS_TABLE_COVER';

    public const DECORATION = 'DECORATION';

    public const DESK = 'DESK';

    public const DESKTOPS = 'DESKTOPS';

    public const DETERGENT_TISSUE = 'DETERGENT_TISSUE';

    public const DINING_TABLE = 'DINING_TABLE';

    public const DISHWASHER = 'DISHWASHER';

    public const DIVING_WATERSPORTS = 'DIVING_WATERSPORTS';

    public const DOG = 'DOG';

    public const DRINK_MAKER = 'DRINK_MAKER';

    public const DRUMS_PERCUSSION = 'DRUMS_PERCUSSION';

    public const EDUCATION = 'EDUCATION';

    public const EDUCATIONAL = 'EDUCATIONAL';

    public const EVENT = 'EVENT';

    public const EVENTS_SPORTS = 'EVENTS_SPORTS';

    public const FAN_VENTILATOR_HUMIDIFIER = 'FAN_VENTILATOR_HUMIDIFIER';

    public const FARM_ANIMALS = 'FARM_ANIMALS';

    public const FIGURINES = 'FIGURINES';

    public const FISH = 'FISH';

    public const FISHING = 'FISHING';

    public const FOOD_AND_DRINK = 'FOOD_AND_DRINK';

    public const FOOD_MILL = 'FOOD_MILL';

    public const FOR_SALE = 'FOR_SALE';

    public const FURNITURE_WOOD = 'FURNITURE_WOOD';

    public const GAME_CONSOLES_AND_VIDEO_GAMES = 'GAME_CONSOLES_AND_VIDEO_GAMES';

    public const GARDEN_AND_LANDSCAPING = 'GARDEN_AND_LANDSCAPING';

    public const GIFT_CERTIFICATE = 'GIFT_CERTIFICATE';

    public const GUITAR_BASS_AMPLIFIER = 'GUITAR_BASS_AMPLIFIER';

    public const HEALTH_BEAUTY = 'HEALTH_BEAUTY';

    public const HEAVY = 'HEAVY';

    public const HISTORICAL = 'HISTORICAL';

    public const HISTORICAL_OBJECTS = 'HISTORICAL_OBJECTS';

    public const HOBBY_COLLECTIBLES = 'HOBBY_COLLECTIBLES';

    public const HOME_CATERING = 'HOME_CATERING';

    public const HOME_LIGHTING = 'HOME_LIGHTING';

    public const HORSES_EQUESTRIAN = 'HORSES_EQUESTRIAN';

    public const INDUSTRIAL_MACHINERY = 'INDUSTRIAL_MACHINERY';

    public const INDUSTRIAL_TECHNOLOGY = 'INDUSTRIAL_TECHNOLOGY';

    public const JANITORIAL_CLEANING = 'JANITORIAL_CLEANING';

    public const JEWELRY = 'JEWELRY';

    public const JEWELRY_AND_WATCHES = 'JEWELRY_AND_WATCHES';

    public const JUICERS = 'JUICERS';

    public const LAMPS = 'LAMPS';

    public const LAMPSHADE = 'LAMPSHADE';

    public const LAPTOPS = 'LAPTOPS';

    public const LEISURE_HOBBIES_TOYS = 'LEISURE_HOBBIES_TOYS';

    public const LIGHT = 'LIGHT';

    public const LITERARY = 'LITERARY';

    public const LOST_AND_FOUND = 'LOST_AND_FOUND';

    public const LOST_ANIMALS = 'LOST_ANIMALS';

    public const LOST_THINGS = 'LOST_THINGS';

    public const LUMBAR_PILLOW = 'LUMBAR_PILLOW';

    public const MAGAZINES = 'MAGAZINES';

    public const MAT = 'MAT';

    public const MATTRESS = 'MATTRESS';

    public const MEDIA_ADVERTISING = 'MEDIA_ADVERTISING';

    public const MEDICAL_EQUIPMENT = 'MEDICAL_EQUIPMENT';

    public const MIRROR = 'MIRROR';

    public const MOBILE_PHONES = 'MOBILE_PHONES';

    public const MOBILE_TABLET = 'MOBILE_TABLET';

    public const MOBILE_TABLET_ACCESSORIES = 'MOBILE_TABLET_ACCESSORIES';

    public const MODEM_AND_NETWORK_EQUIPMENT = 'MODEM_AND_NETWORK_EQUIPMENT';

    public const MOQUETTE = 'MOQUETTE';

    public const MOTORCYCLES = 'MOTORCYCLES';

    public const MOVIES_AND_MUSIC = 'MOVIES_AND_MUSIC';

    public const MP3_PLAYER = 'MP3_PLAYER';

    public const MUSICAL_INSTRUMENTS = 'MUSICAL_INSTRUMENTS';

    public const NATURAL_PLANTS = 'NATURAL_PLANTS';

    public const OFFICES = 'OFFICES';

    public const OFFICE_DECORATION = 'OFFICE_DECORATION';

    public const OTHER_APPLIANCES = 'OTHER_APPLIANCES';

    public const OVEN_BAKING_APPLIANCES = 'OVEN_BAKING_APPLIANCES';

    public const PAINTINGS_PICTURE = 'PAINTINGS_PICTURE';

    public const PARTS_ACCESSORIES = 'PARTS_ACCESSORIES';

    public const PARTS_AND_ACCESSORIES = 'PARTS_AND_ACCESSORIES';

    public const PERSONAL_TOYS = 'PERSONAL_TOYS';

    public const PHONE_DESK = 'PHONE_DESK';

    public const PIANO_KEYBOARD = 'PIANO_KEYBOARD';

    public const PICTORIAL_CARPET = 'PICTORIAL_CARPET';

    public const POT_KETTLE = 'POT_KETTLE';

    public const PRINTER_SCANER_COPIER = 'PRINTER_SCANER_COPIER';

    public const RANGE_HOOD = 'RANGE_HOOD';

    public const REFRIGERATOR_FREEZER = 'REFRIGERATOR_FREEZER';

    public const RELIGIOUS = 'RELIGIOUS';

    public const RENTAL = 'RENTAL';

    public const REPTILE = 'REPTILE';

    public const RESEARCH = 'RESEARCH';

    public const RHINESTONES = 'RHINESTONES';

    public const RODENTS_RABBITS = 'RODENTS_RABBITS';

    public const RUBBER_CARPET = 'RUBBER_CARPET';

    public const RUGS_WOOLEN_CLOTH = 'RUGS_WOOLEN_CLOTH';

    public const SALES_MARKETING = 'SALES_MARKETING';

    public const SEWING_ACCESSORIES = 'SEWING_ACCESSORIES';

    public const SEWING_KNITTING = 'SEWING_KNITTING';

    public const SEWING_MACHINE = 'SEWING_MACHINE';

    public const SHOES_BELT_BAG = 'SHOES_BELT_BAG';

    public const SHOE_RACK_DRAWER = 'SHOE_RACK_DRAWER';

    public const SHOP_AND_CASH = 'SHOP_AND_CASH';

    public const SHOP_RESTAURANT = 'SHOP_RESTAURANT';

    public const SIM_CARD = 'SIM_CARD';

    public const SLEEP_GOODS = 'SLEEP_GOODS';

    public const SPORT = 'SPORT';

    public const SPORT_LEISURE = 'SPORT_LEISURE';

    public const STATIONERY = 'STATIONERY';

    public const STEAM_IRON = 'STEAM_IRON';

    public const STEREO_SURROUND = 'STEREO_SURROUND';

    public const STROLLERS_AND_ACCESSORIES = 'STROLLERS_AND_ACCESSORIES';

    public const TABLECLOTHS = 'TABLECLOTHS';

    public const TABLET = 'TABLET';

    public const TEACHING = 'TEACHING';

    public const THEATRE_AND_CINEMA = 'THEATRE_AND_CINEMA';

    public const TICKET = 'TICKET';

    public const TICKETS_SPORTS = 'TICKETS_SPORTS';

    public const TOOLBOX = 'TOOLBOX';

    public const TRADITIONAL = 'TRADITIONAL';

    public const TRAINING = 'TRAINING';

    public const TRANSPORT = 'TRANSPORT';

    public const TRANSPORTATION = 'TRANSPORTATION';

    public const TV_PROJECTOR = 'TV_PROJECTOR';

    public const TV_STAND = 'TV_STAND';

    public const VACUUMS_CLEANER = 'VACUUMS_CLEANER';

    public const VENTILATION_COOLING_HEATING = 'VENTILATION_COOLING_HEATING';

    public const VIDEO_DVDPLAYER = 'VIDEO_DVDPLAYER';

    public const VIOLINS = 'VIOLINS';

    public const VOLUNTEERS = 'VOLUNTEERS';

    public const WALL_CLOCK = 'WALL_CLOCK';

    public const WASHING_CLEANING = 'WASHING_CLEANING';

    public const WASHING_MACHINES = 'WASHING_MACHINES';

    public const WATCHES = 'WATCHES';

    public const WATER_COOLER = 'WATER_COOLER';

    public const WATER_COOLER_REFINERY = 'WATER_COOLER_REFINERY';

    public const WC_ACCESSORIES = 'WC_ACCESSORIES';

    public const WIND = 'WIND';

    public const WINTER_SPORTS = 'WINTER_SPORTS';

    public const WORK_EQUIPMENT = 'WORK_EQUIPMENT';

    public const YARN_LIGHTS = 'YARN_LIGHTS';

    public const ARTICLE_MAGNIFIER = 'ARTICLE_MAGNIFIER';

    public const ARTICLE_MAGNIFIER_F = 'ARTICLE_MAGNIFIER_F';

    public const FOOTNOTE = 'FOOTNOTE';

    public const SPARKLES_F = 'SPARKLES_F';

    public const HAND_CLICK = 'HAND_CLICK';

    public const WHATS_APP = 'WHATS_APP';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::KEYBOARD_ARROW_RIGHT,
            self::KEYBOARD_ARROW_LEFT,
            self::ARROW_FORWARD,
            self::REFRESH,
            self::REMOVE,
            self::SEND,
            self::DELETE,
            self::PHOTO_LIBRARY,
            self::ADD,
            self::CLOSE,
            self::CHECKED,
            self::CHECK_BOX,
            self::CHECK_BOX_OUTLINE_BLANK,
            self::CHAT_DOUBLE,
            self::CONTENT_COPY,
            self::REPORT,
            self::CAT_VEHICLES,
            self::PERSON,
            self::CALL,
            self::CAT_ELECTRONIC_DEVICES,
            self::PLACE,
            self::HISTORY,
            self::CHECK_CIRCLE,
            self::ACCESS_TIME,
            self::INFO_OUTLINE,
            self::PAYMENT,
            self::SHOW_CHART,
            self::CONTACT_PHONE,
            self::TRENDING_UP,
            self::CAR_BODY,
            self::INSPECT,
            self::CAR_TIRES,
            self::CAR_ELECTRONICS,
            self::CAR_ENGINE,
            self::CAR_HYDRAULICS,
            self::CAR_OPTIONS,
            self::CAR_DOCUMENTS,
            self::CANCEL,
            self::WARNING,
            self::HELP,
            self::MONEY,
            self::KARNAMEH,
            self::EDIT,
            self::SUPPORT,
            self::CAR_INSPECTED,
            self::TERMS,
            self::LADDER_COLLECTION,
            self::HOUSE_INSPECTION,
            self::ADD_CIRCLE,
            self::GAVEL,
            self::LADDER_GROUP,
            self::VISIBILITY,
            self::TIMER,
            self::LOCK,
            self::BLOCK,
            self::EMAIL_OUTLINE,
            self::ASSIGNMENT_IND,
            self::TOC,
            self::EXIT_TO_APP,
            self::HELP_OUTLINE,
            self::TELEPHONE,
            self::EVENT_NOTE,
            self::COMMUNITY,
            self::REAL_ESTATE,
            self::VR,
            self::NUM_1,
            self::NUM_2,
            self::NUM_3,
            self::NUM_4,
            self::NUM_5,
            self::NUM_6,
            self::NUM_7,
            self::NUM_8,
            self::NUM_9,
            self::ELEVATOR,
            self::PARKING,
            self::CABINET,
            self::BALCONY,
            self::TEXTURE,
            self::WC,
            self::SNOWFLAKE,
            self::SUNNY,
            self::THERMOMETER,
            self::VERIFIED,
            self::SETTINGS,
            self::CREDIT_ACCOUNT,
            self::CAR_AUCTION,
            self::CONCIERGE_SALE,
            self::INFO,
            self::MARKETPLACE_GENERAL,
            self::MARKETPLACE_HOME,
            self::MARKETPLACE_PERSONAL,
            self::MARKETPLACE_ELECTRONIC_DEVICES,
            self::INDICATOR_F,
            self::SHARE,
            self::CAR_INSPECTION,
            self::VERIFIED_USER,
            self::MARKETPLACE_LIST,
            self::BINDER,
            self::STAR,
            self::CAR_AMENITY,
            self::CAR_SAFETY,
            self::CAR_EQUIPMENT,
            self::BUSINESS_REAL_ESTATE_AGENCY,
            self::BUSINESS_MARKETPLACE,
            self::BUSINESS_AUTO_DEALERSHIP,
            self::LOCAL_SHIPPING,
            self::MOPED,
            self::TEXT_SMS_OUTLINE,
            self::PLACE_F,
            self::MOBILE_FRIENDLY,
            self::STAR_BORDER,
            self::IMAGE_OUTLINE,
            self::ARTICLE_OUTLINE,
            self::POST_FEEDBACK,
            self::DOWNLOAD,
            self::FILTER,
            self::SUPPORT_AGENT,
            self::MORE_VERT,
            self::BOOKMARK,
            self::BOOKMARK_BORDER,
            self::GIFT,
            self::ANALYTICS,
            self::STORE,
            self::STORE_OUTLINE,
            self::CAT_BUSINESSES,
            self::CAT_FOR_THE_HOME,
            self::CAT_SERVICES,
            self::CAT_PERSONAL,
            self::CAT_LEISURE_HOBBIES,
            self::CAT_JOBS,
            self::SCHOOL,
            self::NOTE,
            self::LOGOUT,
            self::PERSON_ADD,
            self::ADVERT,
            self::ADVERT_OUTLINE,
            self::ACCESS_TIME_OUTLINE,
            self::NOTE_OUTLINE,
            self::PAYMENT_OUTLINE,
            self::INSTAGRAM,
            self::TAG_CHECK_CIRCLE,
            self::FULLSCREEN,
            self::ADD_CIRCLE_OUTLINE,
            self::NOTE_ADD_OUTLINE,
            self::BRAND_ALFA_ROMEO,
            self::BRAND_AMICO,
            self::BRAND_ARIO,
            self::BRAND_ARISAN,
            self::BRAND_AUDI,
            self::BRAND_BAIC,
            self::BRAND_BESTURN,
            self::BRAND_BISU,
            self::BRAND_BMW,
            self::BRAND_BORGWARD,
            self::BRAND_BRILLIANCE,
            self::BRAND_BUICK,
            self::BRAND_BYD,
            self::BRAND_CAPRA,
            self::BRAND_CHANGAN,
            self::BRAND_CHERY,
            self::BRAND_CHEVROLET,
            self::BRAND_CITROEN,
            self::BRAND_DAEWOO,
            self::BRAND_DATSUN,
            self::BRAND_DEER,
            self::BRAND_DELICA,
            self::BRAND_DENA,
            self::BRAND_DIGNITY,
            self::BRAND_DODGE,
            self::BRAND_DOMY,
            self::BRAND_DONGFENG,
            self::BRAND_DS,
            self::BRAND_FARDA,
            self::BRAND_FAW,
            self::BRAND_FIAT,
            self::BRAND_FIDELITY,
            self::BRAND_FORD,
            self::BRAND_FOTON,
            self::BRAND_GAC_GONOW,
            self::BRAND_GEELY,
            self::BRAND_GREATWALL,
            self::BRAND_HAFEI_LOBO,
            self::BRAND_HAIMA,
            self::BRAND_HANTENG,
            self::BRAND_HAVAL,
            self::BRAND_HILLMAN,
            self::BRAND_HONDA,
            self::BRAND_HUMMER,
            self::BRAND_HYOSOW,
            self::BRAND_HYUNDAI,
            self::BRAND_IRANKHODRO_VAN,
            self::BRAND_ISUZU,
            self::BRAND_IVECO,
            self::BRAND_JAC,
            self::BRAND_JAGUAR,
            self::BRAND_JEEP,
            self::BRAND_JMC,
            self::BRAND_JOYLONG,
            self::BRAND_KIA,
            self::BRAND_KMC,
            self::BRAND_LADA,
            self::BRAND_LAMBORGHINI,
            self::BRAND_LAND_ROVER,
            self::BRAND_LANDMARK,
            self::BRAND_LEXUS,
            self::BRAND_LIFAN,
            self::BRAND_LOTUS,
            self::BRAND_LUXGEN,
            self::BRAND_MASERATI,
            self::BRAND_MAXUS,
            self::BRAND_MAZDA,
            self::BRAND_MERCEDESBENZ,
            self::BRAND_MG,
            self::BRAND_MINI,
            self::BRAND_MITSUBISHI,
            self::BRAND_MVM,
            self::BRAND_NARVAN,
            self::BRAND_NISSAN,
            self::BRAND_OLDSMOBILE,
            self::BRAND_OPEL,
            self::BRAND_PAYKAN,
            self::BRAND_PAZHAN,
            self::BRAND_PEUGEOT,
            self::BRAND_PONTIAC,
            self::BRAND_PORSCHE,
            self::BRAND_PRIDE,
            self::BRAND_PROTON,
            self::BRAND_QUICK,
            self::BRAND_RAYEN,
            self::BRAND_RENAULT,
            self::BRAND_RICH,
            self::BRAND_RIGAN,
            self::BRAND_RUNNA,
            self::BRAND_SAINA,
            self::BRAND_SAIPA,
            self::BRAND_SAMAND,
            self::BRAND_SEAT,
            self::BRAND_SHAHIN,
            self::BRAND_SINAD,
            self::BRAND_SMART,
            self::BRAND_SSANGYONG,
            self::BRAND_SUBARU,
            self::BRAND_SUZUKI,
            self::BRAND_SWM,
            self::BRAND_TARA,
            self::BRAND_TIBA,
            self::BRAND_TOYOTA,
            self::BRAND_UAZ,
            self::BRAND_VOLKSWAGEN,
            self::BRAND_VOLVO,
            self::BRAND_ZAMYAD,
            self::BRAND_ZOTYE,
            self::BRAND_SOUEAST,
            self::ARCHWAY,
            self::METRO,
            self::POI,
            self::STREET_SIGN,
            self::TREES,
            self::EARNEST,
            self::RESTAURANT,
            self::BACKPACK,
            self::STETHOSCOPE,
            self::MOSQUE,
            self::HOSPITAL,
            self::CAPSULE,
            self::BANK,
            self::CART,
            self::SHOPPING,
            self::BRAND_CHRYSLER,
            self::BRAND_DAIHATSU,
            self::BRAND_FOWNIX,
            self::BRAND_ROLLSROYCE,
            self::TUNE,
            self::EXCHANGE,
            self::BABY,
            self::BAGUETTE,
            self::BUS,
            self::COFFEE,
            self::FRUIT,
            self::GAS_STATION,
            self::GYM,
            self::HAMBURGER,
            self::HIGHWAY,
            self::MEDIC,
            self::SCHOOL_OUTLINE,
            self::TAXI,
            self::CAMERA,
            self::CAMERA_O,
            self::EYE_OFF,
            self::BRAND_DAYUN,
            self::BRAND_MAXMOTOR,
            self::VIDEOCAM,
            self::BRAND_ACER,
            self::BRAND_ALCATEL,
            self::BRAND_AMAZON,
            self::BRAND_APPLE,
            self::BRAND_ARCHOS,
            self::BRAND_ASUS,
            self::BRAND_BLACKBERRY,
            self::BRAND_BLU,
            self::BRAND_CATERPILLAR,
            self::BRAND_ENERGIZER,
            self::BRAND_GIGABYTE,
            self::BRAND_GIONEE,
            self::BRAND_GLX,
            self::BRAND_GOOGLE,
            self::BRAND_GPLUS,
            self::BRAND_HONOR,
            self::BRAND_HTC,
            self::BRAND_HUAWEI,
            self::BRAND_LENOVO,
            self::BRAND_LG,
            self::BRAND_MEIZU,
            self::BRAND_MICROMAX,
            self::BRAND_MICROSOFT,
            self::BRAND_MOTOROLA,
            self::BRAND_NOKIA,
            self::BRAND_ONEPLUS,
            self::BRAND_OPPO,
            self::BRAND_PANASONIC,
            self::BRAND_PHILIPS,
            self::BRAND_PIXEL,
            self::BRAND_PRESTIGIO,
            self::BRAND_RAZER,
            self::BRAND_REALME,
            self::BRAND_SAMSUNG,
            self::BRAND_SHARP,
            self::BRAND_SONY_ERICSSON,
            self::BRAND_SONY,
            self::BRAND_VERTU,
            self::BRAND_VIVO,
            self::BRAND_XIAOMI,
            self::BRAND_YOTA,
            self::BRAND_ZTE,
            self::BRAND_INROADS,
            self::VIDEOCAM_O,
            self::SHIELD_PHONE,
            self::SHIELD_PHONE_O,
            self::BRAND_LAMARI,
            self::VERIFIED_GREEN,
            self::CHART,
            self::CHART_O,
            self::LAUNCH,
            self::WALLET,
            self::TRASH_O,
            self::TRASH_F,
            self::BRAND_RESPECT,
            self::BRAND_TIGARD,
            self::FILE,
            self::FILE_O,
            self::IMAGE_OUTLINE_O,
            self::CONTACT_PHONE_O,
            self::PUZZLE,
            self::PUZZLE_OUTLINE,
            self::CALL_OUTGOING,
            self::CALL_INCOMING,
            self::CALL_MISSED,
            self::CALL_BLOCKED,
            self::ARCHIVE,
            self::ARCHIVE_O,
            self::CHAT_BUBBLE,
            self::CHAT_BUBBLE_F,
            self::MOBILE_1,
            self::MOBILE_2,
            self::MOBILE_3,
            self::MOBILE_4,
            self::MOBILE_5,
            self::MOBILE_6,
            self::MOBILE_7,
            self::CARPET_1,
            self::CARPET_2,
            self::CARPET_3,
            self::CARPET_4,
            self::CARPET_5,
            self::CARPET_6,
            self::SOFA_1,
            self::SOFA_2,
            self::SOFA_3,
            self::SOFA_4,
            self::SOFA_5,
            self::SOFA_6,
            self::LIGHTS_2,
            self::LIGHTS_1,
            self::LIGHTS_3,
            self::LIGHTS_4,
            self::LIGHTS_5,
            self::BATTERY_CHARGING,
            self::BATTERY_HORIZ_075,
            self::BATTERY_PROFILE,
            self::BUILD_CIRCLE,
            self::HEADPHONES,
            self::INVENTORY,
            self::SMARTPHONE,
            self::HOME_INSPECTION,
            self::MOBILE_INSPECTION,
            self::CAR_COLOR_BLUE,
            self::CAR_COLOR_CHERRY,
            self::CAR_COLOR_PERSIANBLUE,
            self::CAR_COLOR_EGGPLANT,
            self::CAR_COLOR_BRONZE,
            self::CAR_COLOR_BEIGE,
            self::CAR_COLOR_PURPLE,
            self::CAR_COLOR_ONIONSKIN,
            self::CAR_COLOR_TITANIUM,
            self::CAR_COLOR_GRAY,
            self::CAR_COLOR_KHAKI,
            self::CAR_COLOR_SLATEGRAY,
            self::CAR_COLOR_CHARCOAL,
            self::CAR_COLOR_YELLOW,
            self::CAR_COLOR_CRIMSON,
            self::CAR_COLOR_OLIVE,
            self::CAR_COLOR_GREEN,
            self::CAR_COLOR_LIGHTSLATEGRAY,
            self::CAR_COLOR_NAVYBLUE,
            self::CAR_COLOR_WHITE,
            self::CAR_COLOR_OYSTERWHITE,
            self::CAR_COLOR_GOLDEN,
            self::CAR_COLOR_LIGHTGRAY,
            self::CAR_COLOR_WARMGRAY,
            self::CAR_COLOR_JUJUBE,
            self::CAR_COLOR_RED,
            self::CAR_COLOR_BROWN,
            self::CAR_COLOR_CARBONBLACK,
            self::CAR_COLOR_DARKRED,
            self::CAR_COLOR_COPPER,
            self::CAR_COLOR_BLACK,
            self::CAR_COLOR_MOCHA,
            self::CAR_COLOR_ORANGE,
            self::CAR_COLOR_BLUESILVER,
            self::CAR_COLOR_SILVER,
            self::CAR_COLOR_DIMGRAY,
            self::CAR_COLOR_JADEGREEN,
            self::DIVAR_LOGO,
            self::CAR_COLOR_CREAM,
            self::CAR_FRONT_SIDE,
            self::CAR_BACK_SIDE,
            self::CAR_DRIVER_SIDE,
            self::CAR_PASSENGER_SIDE,
            self::CAR_ODOMETER,
            self::CRAFTSMEN,
            self::KITCHEN_UTENSILS,
            self::STOVES_HEATERS_FIREPLACES,
            self::TRAVEL_PACKAGES,
            self::WATER_HEATER_PACKAGE_RADIATOR,
            self::STAIRS,
            self::ACCESSIBILITY,
            self::MAP_VIEW,
            self::THUMB_DOWN,
            self::THUMB_UP,
            self::VIDEOCAM_PLUS,
            self::BADGE,
            self::BADGE_F,
            self::RADIO_BUTTON_UNCHECKED,
            self::POLICE,
            self::SORT_ASCENDING,
            self::BUSINESS_PERSONAL,
            self::BRAND_XTRIM,
            self::BRAND_BESTUNE,
            self::BRAND_GAC,
            self::BRAND_VENUCIA,
            self::BRAND_VGV,
            self::BRAND_ZX_AUTO,
            self::BRAND_QINGLING,
            self::BUSINESS_JOBS,
            self::SHIELD_CHECK_CIRCLE,
            self::SCRIPT_TEXT,
            self::DOT_INDICATOR,
            self::CLOCK,
            self::MAP_MARKER,
            self::TOMAN_SIGN,
            self::CHECK_DECOGRAM,
            self::LADDER,
            self::RUNNING_MAN,
            self::CALENDAR_TEXT,
            self::HOME,
            self::ADMINISTRATIVE_DOC,
            self::ANALOG_WATCH,
            self::ANKLE_BOOTS,
            self::BARTER,
            self::BOOTS,
            self::BRIEFCASE,
            self::CAPACITY,
            self::CARPET_DIMENSIONS,
            self::CHAIRS,
            self::CHANDELIER,
            self::COLOR_BEAKER,
            self::CONDITION,
            self::CONTROLLER,
            self::COSMETICS,
            self::CPU,
            self::DIGITAL_WATCH,
            self::DOOR,
            self::DRESS_SHOES,
            self::ELECTRICAL,
            self::FAKE_BADGE,
            self::FANNY_PACK,
            self::FURNITURE,
            self::FURNITURE_CLASSIC,
            self::FURNITURE_SOFA,
            self::HANDBAG,
            self::HDMI,
            self::HERBAL_PILLS,
            self::HOME_AREA,
            self::INSTALLMENT_SALE,
            self::IRANCELL,
            self::IRAN_MAP,
            self::JEWELRY_ANKLET,
            self::JEWELRY_BRACELET,
            self::JEWELRY_EARRINGS,
            self::JEWELRY_NECKLACE,
            self::JEWELRY_RING,
            self::JEWELRY_SET,
            self::LAN,
            self::LOAFERS,
            self::MAN,
            self::MAN_AND_WOMAN,
            self::MATERIAL,
            self::MCI,
            self::MEDICAL,
            self::MEMORY,
            self::MODEM,
            self::MONEY_BILLS,
            self::NINTENDO,
            self::ORIGINAL_BADGE,
            self::PAPER_DEED,
            self::PARKING_LOT,
            self::PERFUMES,
            self::PLAY_STATION,
            self::RAM,
            self::RECEIVING_HAND,
            self::RIGHTEL,
            self::SANDALS,
            self::SCISSORS,
            self::SCREEN_SIZE,
            self::SHAKING_HANDS,
            self::SHOULDER_BAG,
            self::SIDE_TABLE,
            self::SIM,
            self::SIM_HOLDER,
            self::SKIN_CARE,
            self::SLIPPERS,
            self::SMART_WATCH,
            self::SNEAKERS,
            self::SPEEDOMETER,
            self::SPORT_BAG,
            self::STAIRCASE,
            self::STORAGE,
            self::UMBRELLA,
            self::USB,
            self::WOMAN,
            self::WORLD_MAP,
            self::XBOX,
            self::SHIELD_CHECK,
            self::CAR,
            self::BUILDING,
            self::STOP_WATCH,
            self::CHATBOT,
            self::CHATBOT_OUTLINE,
            self::APARTMENT_RENT,
            self::APARTMENT_SELL,
            self::COMMERCIAL_RENT,
            self::COMMERCIAL_SELL,
            self::HOUSE_VILLA_RENT,
            self::HOUSE_VILLA_SELL,
            self::INDUSTRY_AGRICULTURE_BUSINESS_RENT,
            self::INDUSTRY_AGRICULTURE_BUSINESS_SELL,
            self::OFFICE_RENT,
            self::OFFICE_SELL,
            self::PARTNERSHIP,
            self::PLOT_OLD,
            self::PRESELL,
            self::REAL_ESTATE_SERVICES,
            self::RESIDENTIAL_RENT,
            self::RESIDENTIAL_SELL,
            self::SHOP_RENT,
            self::SHOP_SELL,
            self::SUITE_APARTMENT,
            self::TEMPORARY_RENT,
            self::VILLA,
            self::WORKSPACE,
            self::IMAGE_MULTIPLE,
            self::SHATEL_MOBILE,
            self::MEGAPHONE_F,
            self::MEGAPHONE,
            self::YEKTANET,
            self::TAPSELL,
            self::DAART,
            self::CLOSE_CIRCLE,
            self::CLOSE_CIRCLE_F,
            self::ACCESSORIES,
            self::ACCOUNTING_AND_FINANCE,
            self::ACCOUNTING_FINANCE_LEGAL,
            self::ADMINISTRATION_AND_HR,
            self::AIR_CONDITIONING_FAN_COIL,
            self::ANIMALS,
            self::APPLIANCE,
            self::ARTIFICIAL_FLOWER,
            self::AUDIO_VIDEO,
            self::BABY_AND_TOYS,
            self::BALL_SPORTS,
            self::BARBERSHOP_AND_BEAUTYSALON,
            self::BATCH,
            self::BATHROOMS,
            self::BATHROOM_ACCESSORIES,
            self::BEAUTY_AND_HAIRCARE,
            self::BED_PILLOW_BLANKET,
            self::BED_SERVICE,
            self::BED_SHEET,
            self::BICYCLE,
            self::BIRDS,
            self::BOAT,
            self::BOOKCASE_SHELF,
            self::BOOK_STUDENT_LITERATURE,
            self::BUFFET_SHOWCASES,
            self::BUILDING_EQUIPMENT,
            self::BUS_METRO_TRAIN,
            self::CAFE_AND_RESTAURANT,
            self::CAMERA_CAMCODERS,
            self::CAMPING_OUTDOOR,
            self::CARE_HEALTH_BEAUTY,
            self::CARPET,
            self::CARPET_MOQUETTE,
            self::CARS,
            self::CAR_AND_MOTOR,
            self::CAT,
            self::CATERING,
            self::CCTV,
            self::CHAIR_BENCH,
            self::CHANDELIERS,
            self::CHILDRENS_CLOTHING_AND_SHOE,
            self::CHILDRENS_FURNITURE,
            self::CHILD_CAR_SEAT,
            self::CLASSIC,
            self::CLEANING,
            self::CLEANING_SUPPLIES,
            self::CLOTHES_RACK,
            self::CLOTHING,
            self::CLOTHING_AND_SHOES,
            self::COIN_STAMP,
            self::COMPUTERS,
            self::COMPUTER_AND_IT,
            self::COMPUTER_AND_MOBILE,
            self::CONCERT,
            self::CONFERENCE_MEETING,
            self::CONSTRUCTION_CRAFT,
            self::CONTAINERS,
            self::CONTAINER_ORGANIZERS,
            self::COOKING_UTENSILS,
            self::CRAFTS,
            self::CURTAINS_TABLE_COVER,
            self::DECORATION,
            self::DESK,
            self::DESKTOPS,
            self::DETERGENT_TISSUE,
            self::DINING_TABLE,
            self::DISHWASHER,
            self::DIVING_WATERSPORTS,
            self::DOG,
            self::DRINK_MAKER,
            self::DRUMS_PERCUSSION,
            self::EDUCATION,
            self::EDUCATIONAL,
            self::EVENT,
            self::EVENTS_SPORTS,
            self::FAN_VENTILATOR_HUMIDIFIER,
            self::FARM_ANIMALS,
            self::FIGURINES,
            self::FISH,
            self::FISHING,
            self::FOOD_AND_DRINK,
            self::FOOD_MILL,
            self::FOR_SALE,
            self::FURNITURE_WOOD,
            self::GAME_CONSOLES_AND_VIDEO_GAMES,
            self::GARDEN_AND_LANDSCAPING,
            self::GIFT_CERTIFICATE,
            self::GUITAR_BASS_AMPLIFIER,
            self::HEALTH_BEAUTY,
            self::HEAVY,
            self::HISTORICAL,
            self::HISTORICAL_OBJECTS,
            self::HOBBY_COLLECTIBLES,
            self::HOME_CATERING,
            self::HOME_LIGHTING,
            self::HORSES_EQUESTRIAN,
            self::INDUSTRIAL_MACHINERY,
            self::INDUSTRIAL_TECHNOLOGY,
            self::JANITORIAL_CLEANING,
            self::JEWELRY,
            self::JEWELRY_AND_WATCHES,
            self::JUICERS,
            self::LAMPS,
            self::LAMPSHADE,
            self::LAPTOPS,
            self::LEISURE_HOBBIES_TOYS,
            self::LIGHT,
            self::LITERARY,
            self::LOST_AND_FOUND,
            self::LOST_ANIMALS,
            self::LOST_THINGS,
            self::LUMBAR_PILLOW,
            self::MAGAZINES,
            self::MAT,
            self::MATTRESS,
            self::MEDIA_ADVERTISING,
            self::MEDICAL_EQUIPMENT,
            self::MIRROR,
            self::MOBILE_PHONES,
            self::MOBILE_TABLET,
            self::MOBILE_TABLET_ACCESSORIES,
            self::MODEM_AND_NETWORK_EQUIPMENT,
            self::MOQUETTE,
            self::MOTORCYCLES,
            self::MOVIES_AND_MUSIC,
            self::MP3_PLAYER,
            self::MUSICAL_INSTRUMENTS,
            self::NATURAL_PLANTS,
            self::OFFICES,
            self::OFFICE_DECORATION,
            self::OTHER_APPLIANCES,
            self::OVEN_BAKING_APPLIANCES,
            self::PAINTINGS_PICTURE,
            self::PARTS_ACCESSORIES,
            self::PARTS_AND_ACCESSORIES,
            self::PERSONAL_TOYS,
            self::PHONE_DESK,
            self::PIANO_KEYBOARD,
            self::PICTORIAL_CARPET,
            self::POT_KETTLE,
            self::PRINTER_SCANER_COPIER,
            self::RANGE_HOOD,
            self::REFRIGERATOR_FREEZER,
            self::RELIGIOUS,
            self::RENTAL,
            self::REPTILE,
            self::RESEARCH,
            self::RHINESTONES,
            self::RODENTS_RABBITS,
            self::RUBBER_CARPET,
            self::RUGS_WOOLEN_CLOTH,
            self::SALES_MARKETING,
            self::SEWING_ACCESSORIES,
            self::SEWING_KNITTING,
            self::SEWING_MACHINE,
            self::SHOES_BELT_BAG,
            self::SHOE_RACK_DRAWER,
            self::SHOP_AND_CASH,
            self::SHOP_RESTAURANT,
            self::SIM_CARD,
            self::SLEEP_GOODS,
            self::SPORT,
            self::SPORT_LEISURE,
            self::STATIONERY,
            self::STEAM_IRON,
            self::STEREO_SURROUND,
            self::STROLLERS_AND_ACCESSORIES,
            self::TABLECLOTHS,
            self::TABLET,
            self::TEACHING,
            self::THEATRE_AND_CINEMA,
            self::TICKET,
            self::TICKETS_SPORTS,
            self::TOOLBOX,
            self::TRADITIONAL,
            self::TRAINING,
            self::TRANSPORT,
            self::TRANSPORTATION,
            self::TV_PROJECTOR,
            self::TV_STAND,
            self::VACUUMS_CLEANER,
            self::VENTILATION_COOLING_HEATING,
            self::VIDEO_DVDPLAYER,
            self::VIOLINS,
            self::VOLUNTEERS,
            self::WALL_CLOCK,
            self::WASHING_CLEANING,
            self::WASHING_MACHINES,
            self::WATCHES,
            self::WATER_COOLER,
            self::WATER_COOLER_REFINERY,
            self::WC_ACCESSORIES,
            self::WIND,
            self::WINTER_SPORTS,
            self::WORK_EQUIPMENT,
            self::YARN_LIGHTS,
            self::ARTICLE_MAGNIFIER,
            self::ARTICLE_MAGNIFIER_F,
            self::FOOTNOTE,
            self::SPARKLES_F,
            self::HAND_CLICK,
            self::WHATS_APP
        ];
    }
}


