<?php
/**
 * FinderSearchQuery
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;

use \ArrayAccess;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * FinderSearchQuery Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FinderSearchQuery implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'finderSearchQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'brand_model' => 'string[]',
        'credit' => '\Divar\KenarApiClient\Model\FinderSearchQueryNumberRange',
        'only_with_parking' => 'bool',
        'production_year' => '\Divar\KenarApiClient\Model\FinderSearchQueryNumberRange',
        'rent' => '\Divar\KenarApiClient\Model\FinderSearchQueryNumberRange',
        'rooms' => 'string[]',
        'size' => '\Divar\KenarApiClient\Model\FinderSearchQueryNumberRange',
        'usage' => '\Divar\KenarApiClient\Model\FinderSearchQueryNumberRange'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'brand_model' => null,
        'credit' => null,
        'only_with_parking' => null,
        'production_year' => null,
        'rent' => null,
        'rooms' => null,
        'size' => null,
        'usage' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'brand_model' => false,
        'credit' => false,
        'only_with_parking' => false,
        'production_year' => false,
        'rent' => false,
        'rooms' => false,
        'size' => false,
        'usage' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'brand_model' => 'brand_model',
        'credit' => 'credit',
        'only_with_parking' => 'only_with_parking',
        'production_year' => 'production_year',
        'rent' => 'rent',
        'rooms' => 'rooms',
        'size' => 'size',
        'usage' => 'usage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'brand_model' => 'setBrandModel',
        'credit' => 'setCredit',
        'only_with_parking' => 'setOnlyWithParking',
        'production_year' => 'setProductionYear',
        'rent' => 'setRent',
        'rooms' => 'setRooms',
        'size' => 'setSize',
        'usage' => 'setUsage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'brand_model' => 'getBrandModel',
        'credit' => 'getCredit',
        'only_with_parking' => 'getOnlyWithParking',
        'production_year' => 'getProductionYear',
        'rent' => 'getRent',
        'rooms' => 'getRooms',
        'size' => 'getSize',
        'usage' => 'getUsage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('brand_model', $data ?? [], null);
        $this->setIfExists('credit', $data ?? [], null);
        $this->setIfExists('only_with_parking', $data ?? [], null);
        $this->setIfExists('production_year', $data ?? [], null);
        $this->setIfExists('rent', $data ?? [], null);
        $this->setIfExists('rooms', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('usage', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets brand_model
     *
     * @return string[]|null
     */
    public function getBrandModel()
    {
        return $this->container['brand_model'];
    }

    /**
     * Sets brand_model
     *
     * @param string[]|null $brand_model brand_model
     *
     * @return self
     */
    public function setBrandModel($brand_model)
    {
        if (is_null($brand_model)) {
            throw new \InvalidArgumentException('non-nullable brand_model cannot be null');
        }
        $this->container['brand_model'] = $brand_model;

        return $this;
    }

    /**
     * Gets credit
     *
     * @return \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null
     */
    public function getCredit()
    {
        return $this->container['credit'];
    }

    /**
     * Sets credit
     *
     * @param \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null $credit credit
     *
     * @return self
     */
    public function setCredit($credit)
    {
        if (is_null($credit)) {
            throw new \InvalidArgumentException('non-nullable credit cannot be null');
        }
        $this->container['credit'] = $credit;

        return $this;
    }

    /**
     * Gets only_with_parking
     *
     * @return bool|null
     */
    public function getOnlyWithParking()
    {
        return $this->container['only_with_parking'];
    }

    /**
     * Sets only_with_parking
     *
     * @param bool|null $only_with_parking only_with_parking
     *
     * @return self
     */
    public function setOnlyWithParking($only_with_parking)
    {
        if (is_null($only_with_parking)) {
            throw new \InvalidArgumentException('non-nullable only_with_parking cannot be null');
        }
        $this->container['only_with_parking'] = $only_with_parking;

        return $this;
    }

    /**
     * Gets production_year
     *
     * @return \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null
     */
    public function getProductionYear()
    {
        return $this->container['production_year'];
    }

    /**
     * Sets production_year
     *
     * @param \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null $production_year production_year
     *
     * @return self
     */
    public function setProductionYear($production_year)
    {
        if (is_null($production_year)) {
            throw new \InvalidArgumentException('non-nullable production_year cannot be null');
        }
        $this->container['production_year'] = $production_year;

        return $this;
    }

    /**
     * Gets rent
     *
     * @return \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null
     */
    public function getRent()
    {
        return $this->container['rent'];
    }

    /**
     * Sets rent
     *
     * @param \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null $rent rent
     *
     * @return self
     */
    public function setRent($rent)
    {
        if (is_null($rent)) {
            throw new \InvalidArgumentException('non-nullable rent cannot be null');
        }
        $this->container['rent'] = $rent;

        return $this;
    }

    /**
     * Gets rooms
     *
     * @return string[]|null
     */
    public function getRooms()
    {
        return $this->container['rooms'];
    }

    /**
     * Sets rooms
     *
     * @param string[]|null $rooms rooms
     *
     * @return self
     */
    public function setRooms($rooms)
    {
        if (is_null($rooms)) {
            throw new \InvalidArgumentException('non-nullable rooms cannot be null');
        }
        $this->container['rooms'] = $rooms;

        return $this;
    }

    /**
     * Gets size
     *
     * @return \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets usage
     *
     * @return \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null
     */
    public function getUsage()
    {
        return $this->container['usage'];
    }

    /**
     * Sets usage
     *
     * @param \Divar\KenarApiClient\Model\FinderSearchQueryNumberRange|null $usage usage
     *
     * @return self
     */
    public function setUsage($usage)
    {
        if (is_null($usage)) {
            throw new \InvalidArgumentException('non-nullable usage cannot be null');
        }
        $this->container['usage'] = $usage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


