<?php
/**
 * FinderPostExtState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * FinderPostExtState Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FinderPostExtState
{
    /**
     * Possible values of this enum
     */
    public const PUBLISHED = 'PUBLISHED';

    public const REVIEW_REQ = 'REVIEW_REQ';

    public const PAYMENT_REQ = 'PAYMENT_REQ';

    public const RETIRED = 'RETIRED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PUBLISHED,
            self::REVIEW_REQ,
            self::PAYMENT_REQ,
            self::RETIRED
        ];
    }
}


