<?php
/**
 * ManagementPreset
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * ManagementPreset Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManagementPreset
{
    /**
     * Possible values of this enum
     */
    public const LIGHT = 'LIGHT';

    public const CRAFTSMEN = 'CRAFTSMEN';

    public const MOBILE_PHONES = 'MOBILE_PHONES';

    public const APARTMENT_SELL = 'APARTMENT_SELL';

    public const SUITE_APARTMENT = 'SUITE_APARTMENT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LIGHT,
            self::CRAFTSMEN,
            self::MOBILE_PHONES,
            self::APARTMENT_SELL,
            self::SUITE_APARTMENT
        ];
    }
}


