<?php
/**
 * OAuthScopeScope
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * OAuthScopeScope Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OAuthScopeScope
{
    /**
     * Possible values of this enum
     */
    public const POST_ADDON_CREATE = 'POST_ADDON_CREATE';

    public const USER_PHONE = 'USER_PHONE';

    public const USER_ID = 'USER_ID';

    public const USER_ADDON_CREATE = 'USER_ADDON_CREATE';

    public const CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND';

    public const CHAT_CONVERSATION_READ = 'CHAT_CONVERSATION_READ';

    public const USER_POSTS_GET = 'USER_POSTS_GET';

    public const CHAT_POST_CONVERSATIONS_READ = 'CHAT_POST_CONVERSATIONS_READ';

    public const CHAT_POST_CONVERSATIONS_MESSAGE_SEND = 'CHAT_POST_CONVERSATIONS_MESSAGE_SEND';

    public const CHAT_SUPPLIER_ALL_CONVERSATIONS_READ = 'CHAT_SUPPLIER_ALL_CONVERSATIONS_READ';

    public const CHAT_SUPPLIER_ALL_CONVERSATIONS_MESSAGE_SEND = 'CHAT_SUPPLIER_ALL_CONVERSATIONS_MESSAGE_SEND';

    public const CHAT_BOT_USER_MESSAGE_SEND = 'CHAT_BOT_USER_MESSAGE_SEND';

    public const USER_VERIFICATION_CREATE = 'USER_VERIFICATION_CREATE';

    public const OFFLINE_ACCESS = 'OFFLINE_ACCESS';

    public const OPENID = 'OPENID';

    public const PAYMENT_ALL_POSTS_PRICING_READ = 'PAYMENT_ALL_POSTS_PRICING_READ';

    public const PAYMENT_ALL_POSTS_REORDER = 'PAYMENT_ALL_POSTS_REORDER';

    public const MANAGEMENT_APPS_READ = 'MANAGEMENT_APPS_READ';

    public const MANAGEMENT_APPS_WRITE = 'MANAGEMENT_APPS_WRITE';

    public const POST_ONGOING_IMAGES_GET = 'POST_ONGOING_IMAGES_GET';

    public const USER_POSTS_ADDON_CREATE = 'USER_POSTS_ADDON_CREATE';

    public const POST_EDIT = 'POST_EDIT';

    public const CONVERSATION_SEND_MESSAGE = 'CONVERSATION_SEND_MESSAGE';

    public const BUSINESS_ADDON_CREATE = 'BUSINESS_ADDON_CREATE';

    public const POST_SEMANTIC_CREATE = 'POST_SEMANTIC_CREATE';

    public const NOTIFICATION_ACCESS_REVOCATION = 'NOTIFICATION_ACCESS_REVOCATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::POST_ADDON_CREATE,
            self::USER_PHONE,
            self::USER_ID,
            self::USER_ADDON_CREATE,
            self::CHAT_MESSAGE_SEND,
            self::CHAT_CONVERSATION_READ,
            self::USER_POSTS_GET,
            self::CHAT_POST_CONVERSATIONS_READ,
            self::CHAT_POST_CONVERSATIONS_MESSAGE_SEND,
            self::CHAT_SUPPLIER_ALL_CONVERSATIONS_READ,
            self::CHAT_SUPPLIER_ALL_CONVERSATIONS_MESSAGE_SEND,
            self::CHAT_BOT_USER_MESSAGE_SEND,
            self::USER_VERIFICATION_CREATE,
            self::OFFLINE_ACCESS,
            self::OPENID,
            self::PAYMENT_ALL_POSTS_PRICING_READ,
            self::PAYMENT_ALL_POSTS_REORDER,
            self::MANAGEMENT_APPS_READ,
            self::MANAGEMENT_APPS_WRITE,
            self::POST_ONGOING_IMAGES_GET,
            self::USER_POSTS_ADDON_CREATE,
            self::POST_EDIT,
            self::CONVERSATION_SEND_MESSAGE,
            self::BUSINESS_ADDON_CREATE,
            self::POST_SEMANTIC_CREATE,
            self::NOTIFICATION_ACCESS_REVOCATION
        ];
    }
}


