<?php
/**
 * PremiumPanelBusinessDataSubBusinessType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Divar\KenarApiClient\Model;
use \Divar\KenarApiClient\ObjectSerializer;

/**
 * PremiumPanelBusinessDataSubBusinessType Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PremiumPanelBusinessDataSubBusinessType
{
    /**
     * Possible values of this enum
     */
    public const CAR = 'CAR';

    public const REAL_ESTATE = 'REAL_ESTATE';

    public const JOBS = 'JOBS';

    public const MARKETPLACE = 'MARKETPLACE';

    public const SERVICES = 'SERVICES';

    public const PERSONAL = 'PERSONAL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CAR,
            self::REAL_ESTATE,
            self::JOBS,
            self::MARKETPLACE,
            self::SERVICES,
            self::PERSONAL
        ];
    }
}


