<?php
/**
 * AddonsCreateUserAddonV2BodyTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Divar\KenarApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AddonsCreateUserAddonV2BodyTest Class Doc Comment
 *
 * @category    Class
 * @description AddonsCreateUserAddonV2Body
 * @package     Divar\KenarApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddonsCreateUserAddonV2BodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddonsCreateUserAddonV2Body"
     */
    public function testAddonsCreateUserAddonV2Body()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "widgets"
     */
    public function testPropertyWidgets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "semantic"
     */
    public function testPropertySemantic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ticket_uuid"
     */
    public function testPropertyTicketUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
