<?php
/**
 * AddonsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Divar\KenarApiClient\Test\Api;

use \Divar\KenarApiClient\Configuration;
use \Divar\KenarApiClient\ApiException;
use \Divar\KenarApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddonsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addonsCreatePostAddonV2
     *
     * Attach a new Addon to a post.
     *
     */
    public function testAddonsCreatePostAddonV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsCreateUserAddonV2
     *
     * Attach a new Addon to a user.
     *
     */
    public function testAddonsCreateUserAddonV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsCreateUserAddonV22
     *
     * Attach a new Addon to a user.
     *
     */
    public function testAddonsCreateUserAddonV22()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsDeletePostAddon
     *
     * Delete an Addon from a post.
     *
     */
    public function testAddonsDeletePostAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsDeletePostAddon2
     *
     * Delete an Addon from a post.
     *
     */
    public function testAddonsDeletePostAddon2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsDeleteUserAddon
     *
     * Delete an UserAddon.
     *
     */
    public function testAddonsDeleteUserAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsGetUserAddons
     *
     * Retrieve all UserAddons.
     *
     */
    public function testAddonsGetUserAddons()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addonsGetUserAddons2
     *
     * Retrieve all UserAddons.
     *
     */
    public function testAddonsGetUserAddons2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
