<?php
/**
 * AssetsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Divar\KenarApiClient\Test\Api;

use \Divar\KenarApiClient\Configuration;
use \Divar\KenarApiClient\ApiException;
use \Divar\KenarApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AssetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AssetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for assetsGetBodyStatuses
     *
     * Get available body-status options in Divar vehicle categories.
     *
     */
    public function testAssetsGetBodyStatuses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetBrandModels
     *
     * Get brand models in a Divar category.
     *
     */
    public function testAssetsGetBrandModels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetCategories
     *
     * Get Divar categories.
     *
     */
    public function testAssetsGetCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetCities
     *
     * Get Divar cities.
     *
     */
    public function testAssetsGetCities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetColors
     *
     * Get colors in a Divar category.
     *
     */
    public function testAssetsGetColors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetDistricts
     *
     * Get Divar districts.
     *
     */
    public function testAssetsGetDistricts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetDistricts2
     *
     * Get Divar districts.
     *
     */
    public function testAssetsGetDistricts2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetInternalStorages
     *
     * Get available internal-storage options in Divar mobile/tablet/laptop categories.
     *
     */
    public function testAssetsGetInternalStorages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetOAuthScopes
     *
     * Get KenarDivar OAuth scopes.
     *
     */
    public function testAssetsGetOAuthScopes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetPermissions
     *
     * Get KenarDivar permissions.
     *
     */
    public function testAssetsGetPermissions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetRamMemories
     *
     * Get available ram-memory options in Divar mobile/tablet/laptop categories.
     *
     */
    public function testAssetsGetRamMemories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assetsGetServiceTypes
     *
     * Get available service types in KenarDivar.
     *
     */
    public function testAssetsGetServiceTypes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
