<?php
/**
 * ChatAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Divar\KenarApiClient\Test\Api;

use \Divar\KenarApiClient\Configuration;
use \Divar\KenarApiClient\ApiException;
use \Divar\KenarApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChatAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChatAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chatAPIChatBotSendMessage
     *
     * Send a message to a ChatBot conversation.
     *
     */
    public function testChatAPIChatBotSendMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chatAPIChatBotSendMessage2
     *
     * Send a message to a ChatBot conversation.
     *
     */
    public function testChatAPIChatBotSendMessage2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chatAPIChatBotSendMessage3
     *
     * Send a message to a ChatBot conversation.
     *
     */
    public function testChatAPIChatBotSendMessage3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chatAPIConversationSendMessage
     *
     * Send a message to a conversation.
     *
     */
    public function testChatAPIConversationSendMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chatAPIGenerateUploadToken
     *
     * Generate an upload token.
     *
     */
    public function testChatAPIGenerateUploadToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chatAPIGetConversation
     *
     * Get Conversation by it's ID.
     *
     */
    public function testChatAPIGetConversation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
