<?php
/**
 * LimitedApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Divar\KenarApiClient\Test\Api;

use \Divar\KenarApiClient\Configuration;
use \Divar\KenarApiClient\ApiException;
use \Divar\KenarApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LimitedApiTest Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LimitedApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for paymentGetBalance
     *
     * .
     *
     */
    public function testPaymentGetBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentGetPostPricing
     *
     * Retrieve the cost of the service.
     *
     */
    public function testPaymentGetPostPricing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentGetTransaction
     *
     * .
     *
     */
    public function testPaymentGetTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentReorderPost
     *
     * .
     *
     */
    public function testPaymentReorderPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
