<?php
/**
 * SemanticApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kenar API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Divar\KenarApiClient\Test\Api;

use \Divar\KenarApiClient\Configuration;
use \Divar\KenarApiClient\ApiException;
use \Divar\KenarApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SemanticApiTest Class Doc Comment
 *
 * @category Class
 * @package  Divar\KenarApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SemanticApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for semanticCreatePostSemantic
     *
     * Create Post Semantic.
     *
     */
    public function testSemanticCreatePostSemantic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for semanticCreateUserSemantic
     *
     * Create User Semantic.
     *
     */
    public function testSemanticCreateUserSemantic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for semanticCreateUserSemantic2
     *
     * Create User Semantic.
     *
     */
    public function testSemanticCreateUserSemantic2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for semanticDeleteUserSemantic
     *
     * Delete User Semantic.
     *
     */
    public function testSemanticDeleteUserSemantic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for semanticDeleteUserSemantic2
     *
     * Delete User Semantic.
     *
     */
    public function testSemanticDeleteUserSemantic2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
